apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    {{- include "postgresql-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "postgresql-chart.selectorLabels" . | nindent 4 }}
