/*
 Navicat Premium Data Transfer

 Source Server         : pro-logger
 Source Server Type    : PostgreSQL
 Source Server Version : 80413
 Source Host           : localhost
 Source Database       : rinis_beheer
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 80413
 File Encoding         : utf-8

 Date: 01/27/2016 11:46:56 AM
*/

-- ----------------------------
--  Table structure for uitwisselingen
-- ----------------------------
DROP TABLE IF EXISTS "public"."uitwisselingen";
CREATE TABLE "public"."uitwisselingen" (
	"ber" text NOT NULL,
	"fun" text NOT NULL,
	"lev" text NOT NULL,
	"aan" text NOT NULL,
	"uitwisseling" text,
	"leverancier" text,
	"aanvrager" text,
	"verzender" text,
	"beheer_verzender" text,
	"ontvanger" text,
	"beheer_ontvanger" text,
	"status" text,
	"uitwisselingsnummer" text,
	"projecten" text
)
WITH (OIDS=FALSE);
ALTER TABLE "public"."uitwisselingen" OWNER TO "dias";

-- ----------------------------
--  Records of uitwisselingen
-- ----------------------------
BEGIN;
INSERT INTO "public"."uitwisselingen" VALUES ('651', '101', '0101', '0041', 'SUWI 2', 'UWV WERKbedrijf', 'Inlichtingenbureau', 'UWV WERKbedrijf', '', 'Inlichtingenbureau', '', 'vervallen autorisatie', null, null);
INSERT INTO "public"."uitwisselingen" VALUES ('653', '113', '0101', '0041', 'SUWI 2', 'UWV WERKbedrijf', 'Inlichtingenbureau', 'UWV WERKbedrijf', '', 'Inlichtingenbureau', '', 'vervallen autorisatie', null, null);
INSERT INTO "public"."uitwisselingen" VALUES ('654', '113', '0101', '0041', 'SUWI 2', 'UWV WERKbedrijf', 'Inlichtingenbureau', 'UWV WERKbedrijf', '', 'Inlichtingenbureau', '', 'vervallen autorisatie', null, null);
INSERT INTO "public"."uitwisselingen" VALUES ('656', '124', '0101', '0041', 'SUWI 2', 'UWV WERKbedrijf', 'Inlichtingenbureau', 'UWV WERKbedrijf', '', 'Inlichtingenbureau', '', 'vervallen autorisatie', null, null);
INSERT INTO "public"."uitwisselingen" VALUES ('657', '103', '0101', '0041', 'SUWI 2', 'UWV WERKbedrijf', 'Inlichtingenbureau', 'UWV WERKbedrijf', '', 'Inlichtingenbureau', '', 'vervallen autorisatie', null, null);
INSERT INTO "public"."uitwisselingen" VALUES ('658', '100', '0101', '0041', 'SUWI 2', 'UWV WERKbedrijf', 'Inlichtingenbureau', 'UWV WERKbedrijf', '', 'Inlichtingenbureau', '', 'vervallen autorisatie', null, null);
INSERT INTO "public"."uitwisselingen" VALUES ('655', '104', '0041', '0101', 'SUWI 2', 'Inlichtingenbureau', 'UWV WERKbedrijf', 'Inlichtingenbureau', '', 'UWV WERKbedrijf', '', 'vervallen autorisatie', null, null);
INSERT INTO "public"."uitwisselingen" VALUES ('659', '111', '0041', '0101', 'SUWI 2', 'Inlichtingenbureau', 'UWV WERKbedrijf', 'Inlichtingenbureau', '', 'UWV WERKbedrijf', '', 'vervallen autorisatie', null, null);
INSERT INTO "public"."uitwisselingen" VALUES ('660', '112', '0041', '0101', 'SUWI 2', 'Inlichtingenbureau', 'UWV WERKbedrijf', 'Inlichtingenbureau', '', 'UWV WERKbedrijf', '', 'vervallen autorisatie', null, null);
INSERT INTO "public"."uitwisselingen" VALUES ('652', '111', '0041', '0101', 'SUWI 2', 'Inlichtingenbureau', 'UWV WERKbedrijf', 'Inlichtingenbureau', '', 'UWV WERKbedrijf', '', 'vervallen autorisatie', null, null);
INSERT INTO "public"."uitwisselingen" VALUES ('761', '001', '0101', '0120', 'Grote berichten', 'CWI', 'CBS', 'CWI', 'Beheer_CWI', 'CBS', 'Beheer_CBS', 'vervallen autorisatie', null, null);
INSERT INTO "public"."uitwisselingen" VALUES ('778', '001', '0020', '0030', 'GIPA', 'UWV', 'SVB', 'SVB', 'Beheer_SVB', 'UWV', 'Beheer_UWV', 'autorisatie', '020.030.01', 'N11');
INSERT INTO "public"."uitwisselingen" VALUES ('354', '002', '0050', '0030', 'Broninhouding wanbetalers', 'Zorgverzekeraars', 'SVB', 'SVB', 'Beheer_SVB', 'Zorgverzekeraars', 'Beheer_Zorginstituut Nederland', 'autorisatie', '050.030.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('779', '001', '0020', '0030', 'GIPA', 'UWV', 'SVB', 'UWV', 'Beheer_UWV', 'SVB', 'Beheer_SVB', 'autorisatie', '020.030.01', 'N11');
INSERT INTO "public"."uitwisselingen" VALUES ('750', '001', '0020', '0041', 'GIPA / Grote berichten', 'UWV', 'Inlichtingenbureau', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'UWV', 'Beheer_UWV', 'autorisatie', '020.041.04', 'N31');
INSERT INTO "public"."uitwisselingen" VALUES ('751', '001', '0020', '0041', 'GIPA / Grote berichten', 'UWV', 'Inlichtingenbureau', 'UWV', 'Beheer_UWV', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'autorisatie', '020.041.04', 'N31');
INSERT INTO "public"."uitwisselingen" VALUES ('713', '001', '0510', '0120', 'DUO Grote Berichten service', 'Digikoppeling / DUO', 'CBS', 'Digikoppeling / DUO', 'Beheer_DUO', 'CBS', 'Beheer_CBS', 'autorisatie', '510.120.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('311', '003', '0070', '0030', 'Identificatie en verificatie van sofinummers (IVP)', 'Belastingdienst', 'SVB', 'Belastingdienst', 'Beheer_BD_Incidenten', 'SVB', 'Beheer_SVB', 'autorisatie', '070.030.03', null);
INSERT INTO "public"."uitwisselingen" VALUES ('761', '001', '0020', '0120', 'Grote berichten', 'UWV', 'CBS', 'UWV', 'Beheer_UWV', 'CBS', 'Beheer_CBS', 'autorisatie', '020.120.02', null);
INSERT INTO "public"."uitwisselingen" VALUES ('762', '001', '0020', '0120', 'Grote berichten', 'UWV', 'CBS', 'UWV', 'Beheer_UWV', 'CBS', 'Beheer_CBS', 'autorisatie', '020.120.02', null);
INSERT INTO "public"."uitwisselingen" VALUES ('763', '001', '0020', '0120', 'Grote berichten', 'UWV', 'CBS', 'UWV', 'Beheer_UWV', 'CBS', 'Beheer_CBS', 'autorisatie', '020.120.02', null);
INSERT INTO "public"."uitwisselingen" VALUES ('709', '001', '0510', '0120', 'Digilevering (NHR)', 'Digikoppeling / KvK', 'CBS', 'Digikoppeling / KvK', 'Beheer_???', 'CBS', 'Beheer_CBS', 'autorisatie', '510.120.02', 'N37');
INSERT INTO "public"."uitwisselingen" VALUES ('306', '001', '0061', '0030', 'Detentie', 'DJI', 'SVB', 'DJI', 'Beheer_DJI', 'SVB', 'Beheer_SVB', 'autorisatie', '061.030.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('706', '001', '0070', '0130', 'BTW refund', 'Belastingdienst', 'Digipoort', 'Belastingdienst', 'Beheer_BD_Incidenten', 'Digipoort', 'Beheer_OTP', 'autorisatie', '070.130.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('716', '001', '0070', '0510', 'Fiscaal Akkoord', 'Belastingdienst', 'Digikoppeling / RDW', 'Belastingdienst', 'Beheer_BD_Incidenten', 'Digikoppeling / RDW', 'Beheer_???', 'autorisatie', '070.510.02', null);
INSERT INTO "public"."uitwisselingen" VALUES ('717', '001', '0070', '0510', 'Fiscaal Akkoord', 'Belastingdienst', 'Digikoppeling / RDW', 'Digikoppeling / RDW', 'Beheer_???', 'Belastingdienst', 'Beheer_BD_Incidenten', 'autorisatie', '070.510.02', null);
INSERT INTO "public"."uitwisselingen" VALUES ('721', '001', '0510', '0070', 'eFactureren', 'Digikoppeling / Digipoort', 'Belastingdienst', 'Digikoppeling / Digipoort', 'Beheer_???', 'Belastingdienst', 'Beheer_BD_Incidenten', 'autorisatie', '510.070.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('326', '001', '0030', '0150', 'Gemoedsbezwaarden', 'SVB', 'ZINL', 'SVB', 'Beheer_SVB', 'ZINL', 'Beheer_Zorginstituut Nederland', 'autorisatie', '030.150.02', 'N103');
INSERT INTO "public"."uitwisselingen" VALUES ('409', '041', '0020', '0150', 'Digitale Betaalspecificatie', 'UWV', 'ZINL', 'UWV', 'Beheer_UWV', 'ZINL', 'Beheer_Zorginstituut Nederland', 'vervallen autorisatie', '020.150.01', 'N22');
INSERT INTO "public"."uitwisselingen" VALUES ('306', '001', '0061', '0020', 'Detentie', 'DJI', 'UWV', 'DJI', 'Beheer_DJI', 'UWV', 'Beheer_UWV', 'autorisatie', '061.020.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('708', '001', '0070', '0120', 'Geautomatiseerde Periodieke Aangifte', 'Belastingdienst', 'CBS', 'Belastingdienst', 'Beheer_BD_Incidenten', 'CBS', 'Beheer_CBS', 'autorisatie', '070.120.02', null);
INSERT INTO "public"."uitwisselingen" VALUES ('352', '002', '0050', '0030', 'Broninhouding wanbetalers', 'Zorgverzekeraars', 'SVB', 'Zorgverzekeraars', 'Beheer_Zorginstituut Nederland', 'SVB', 'Beheer_SVB', 'autorisatie', '050.030.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('351', '002', '0050', '0030', 'Broninhouding wanbetalers', 'Zorgverzekeraars', 'SVB', 'Zorgverzekeraars', 'Beheer_Zorginstituut Nederland', 'SVB', 'Beheer_SVB', 'autorisatie', '050.030.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('400', '310', '0020', '0140', 'Inkomstenverhoudingen', 'UWV', 'CAK', 'CAK', 'Beheer_CAK', 'UWV', 'Beheer_UWV', 'autorisatie', '020.140.01', 'N22, N10');
INSERT INTO "public"."uitwisselingen" VALUES ('401', '310', '0020', '0140', 'Inkomstenverhoudingen', 'UWV', 'CAK', 'UWV', 'Beheer_UWV', 'CAK', 'Beheer_CAK', 'autorisatie', '020.140.01', 'N22, N10');
INSERT INTO "public"."uitwisselingen" VALUES ('311', '003', '0070', '0050', 'Identificatie en verificatie van sofinummers (IVP)', 'Belastingdienst', 'Zorgverzekeraars', 'Belastingdienst', 'Beheer_BD_Incidenten', 'Zorgverzekeraars', 'Beheer_VECOZO', 'vervallen autorisatie', '070.050.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('400', '211', '0020', '0060', 'Inkomstenverhoudingen', 'UWV', 'LBIO', 'LBIO', 'Beheer_LBIO', 'UWV', 'Beheer_UWV', 'autorisatie', '020.060.01', 'N10');
INSERT INTO "public"."uitwisselingen" VALUES ('401', '201', '0020', '0060', 'Inkomstenverhoudingen', 'UWV', 'LBIO', 'UWV', 'Beheer_UWV', 'LBIO', 'Beheer_LBIO', 'autorisatie', '020.060.01', 'N10');
INSERT INTO "public"."uitwisselingen" VALUES ('480', '201', '0020', '0140', 'Inkomstenverhoudingen', 'UWV', 'CAK', 'UWV', 'Beheer_UWV', 'CAK', 'Beheer_CAK', 'autorisatie', '020.140.01', 'N10');
INSERT INTO "public"."uitwisselingen" VALUES ('400', '211', '0020', '0080', 'Inkomstenverhoudingen', 'UWV', 'Gerechtsdeurwaarders', 'Gerechtsdeurwaarders', 'Beheer_SNG', 'UWV', 'Beheer_UWV', 'autorisatie', '020.080.01', 'N22, N10');
INSERT INTO "public"."uitwisselingen" VALUES ('401', '201', '0020', '0080', 'Inkomstenverhoudingen', 'UWV', 'Gerechtsdeurwaarders', 'UWV', 'Beheer_UWV', 'Gerechtsdeurwaarders', 'Beheer_SNG', 'autorisatie', '020.080.01', 'N22, N10');
INSERT INTO "public"."uitwisselingen" VALUES ('490', '221', '0020', '0150', 'Inkomstenverhoudingen', 'UWV', 'ZINL', 'UWV', 'Beheer_UWV', 'ZINL', 'Beheer_Zorginstituut Nederland', 'vervallen autorisatie', '020.150.02', 'N22, N10');
INSERT INTO "public"."uitwisselingen" VALUES ('420', '311', '0020', '0080', 'Inkomstenverhoudingen', 'UWV', 'Gerechtsdeurwaarders', 'UWV', 'Beheer_UWV', 'Gerechtsdeurwaarders', 'Beheer_SNG', 'autorisatie', '020.080.01', 'N10');
INSERT INTO "public"."uitwisselingen" VALUES ('400', '211', '0020', '0150', 'Inkomstenverhoudingen', 'UWV', 'ZINL', 'ZINL', 'Beheer_Zorginstituut Nederland', 'UWV', 'Beheer_UWV', 'vervallen autorisatie', '020.150.02', 'N22, N10');
INSERT INTO "public"."uitwisselingen" VALUES ('403', '152', '0020', '0060', 'Inkomstenverhoudingen', 'UWV', 'LBIO', 'LBIO', 'Beheer_LBIO', 'UWV', 'Beheer_UWV', 'autorisatie', '020.060.01', 'N10');
INSERT INTO "public"."uitwisselingen" VALUES ('404', '152', '0020', '0060', 'Inkomstenverhoudingen', 'UWV', 'LBIO', 'LBIO', 'Beheer_LBIO', 'UWV', 'Beheer_UWV', 'autorisatie', '020.060.01', 'N10');
INSERT INTO "public"."uitwisselingen" VALUES ('405', '152', '0020', '0060', 'Inkomstenverhoudingen', 'UWV', 'LBIO', 'UWV', 'Beheer_UWV', 'LBIO', 'Beheer_LBIO', 'autorisatie', '020.060.01', 'N10');
INSERT INTO "public"."uitwisselingen" VALUES ('711', '001', '0510', '0070', 'eMededelen', 'Digikoppeling / RDW', 'Belastingdienst', 'Digikoppeling / RDW', 'Beheer_MijnOverheid_Berichtenbox', 'Belastingdienst', 'Beheer_BD_Incidenten', 'vervallen autorisatie', '510.070.03', 'N9');
INSERT INTO "public"."uitwisselingen" VALUES ('733', '001', '0140', '0120', 'WTCG', 'CAK', 'CBS', 'CAK', 'Beheer_CAK', 'CBS', 'Beheer_CBS', 'autorisatie', '140.120.01', 'N2012-4');
INSERT INTO "public"."uitwisselingen" VALUES ('323', '002', '0020', '0120', 'Werkzoekenden', 'UWV', 'CBS', 'UWV', 'Beheer_UWV', 'CBS', 'Beheer_CBS', 'autorisatie', '020.120.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('CPA001', '0100', '0530', '0041', 'GDK configuratie', 'GDK', 'Inlichtingenbureau', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'GDK', 'Beheer_GDK', 'autorisatie', '530.041.01', 'N2014-261');
INSERT INTO "public"."uitwisselingen" VALUES ('CPA002', '0100', '0530', '0041', 'GDK configuratie', 'GDK', 'Inlichtingenbureau', 'GDK', 'Beheer_GDK', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'autorisatie', '530.041.01', 'N2014-261');
INSERT INTO "public"."uitwisselingen" VALUES ('CPA003', '0100', '0530', '0041', 'GDK configuratie', 'GDK', 'Inlichtingenbureau', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'GDK', 'Beheer_GDK', 'autorisatie', '530.041.01', 'N2014-261');
INSERT INTO "public"."uitwisselingen" VALUES ('CPA004', '0100', '0530', '0041', 'GDK configuratie', 'GDK', 'Inlichtingenbureau', 'GDK', 'Beheer_GDK', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'autorisatie', '530.041.01', 'N2014-261');
INSERT INTO "public"."uitwisselingen" VALUES ('CRT001', '0100', '0530', '0041', 'GDK configuratie', 'GDK', 'Inlichtingenbureau', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'GDK', 'Beheer_GDK', 'autorisatie', '530.041.01', 'N2014-261');
INSERT INTO "public"."uitwisselingen" VALUES ('CRT002', '0100', '0530', '0041', 'GDK configuratie', 'GDK', 'Inlichtingenbureau', 'GDK', 'Beheer_GDK', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'autorisatie', '530.041.01', 'N2014-261');
INSERT INTO "public"."uitwisselingen" VALUES ('JW304', '0100', '0530', '0041', 'Declaratie Jeugd-AWBZ', 'GDK', 'Inlichtingenbureau', 'GDK', 'Beheer_GDK', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'autorisatie', '530.041.02', 'N2014-139');
INSERT INTO "public"."uitwisselingen" VALUES ('JW321', '0100', '0530', '0041', 'Declaratie Jeugd-GGZ', 'GDK', 'Inlichtingenbureau', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'GDK', 'Beheer_GDK', 'autorisatie', '530.041.03', 'N2014-139');
INSERT INTO "public"."uitwisselingen" VALUES ('JW322', '0100', '0530', '0041', 'Declaratie Jeugd-GGZ', 'GDK', 'Inlichtingenbureau', 'GDK', 'Beheer_GDK', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'autorisatie', '530.041.03', 'N2014-139');
INSERT INTO "public"."uitwisselingen" VALUES ('WMO304', '0100', '0530', '0041', 'Declaratie WMO', 'GDK', 'Inlichtingenbureau', 'GDK', 'Beheer_GDK', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'autorisatie', '530.041.04', 'N2014-139');
INSERT INTO "public"."uitwisselingen" VALUES ('JW302', '0100', '0041', '0530', 'Toewijzing Jeugd', 'GDK', 'Inlichtingenbureau', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'GDK', 'Beheer_GDK', 'autorisatie', '041.530.01', 'N2014-139');
INSERT INTO "public"."uitwisselingen" VALUES ('WMO301', '0100', '0041', '0530', 'Toewijzing WMO', 'GDK', 'Inlichtingenbureau', 'GDK', 'Beheer_GDK', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'autorisatie', '041.530.02', 'N2014-139');
INSERT INTO "public"."uitwisselingen" VALUES ('WMO302', '0100', '0041', '0530', 'Toewijzing WMO', 'GDK', 'Inlichtingenbureau', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'GDK', 'Beheer_GDK', 'autorisatie', '041.530.02', 'N2014-139');
INSERT INTO "public"."uitwisselingen" VALUES ('710', '001', '0510', '0070', 'eMededelen', 'Digikoppeling / RDW', 'Belastingdienst', 'Belastingdienst', 'Beheer_BD_Incidenten', 'Digikoppeling / RDW', 'Beheer_MijnOverheid_Berichtenbox', 'vervallen autorisatie', '510.070.03', 'N9');
INSERT INTO "public"."uitwisselingen" VALUES ('385', '001', '0510', '0020', 'Registratie Niet-Ingezetenen (RNI)', 'Digikoppeling / RvIG', 'UWV', 'UWV', 'Beheer_UWV', 'Digikoppeling / RvIG', 'Beheer_RNI', 'autorisatie', '510.020.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('386', '001', '0510', '0020', 'Registratie Niet-Ingezetenen (RNI)', 'Digikoppeling / RvIG', 'UWV', 'Digikoppeling / RvIG', 'Beheer_RNI', 'UWV', 'Beheer_UWV', 'autorisatie', '510.020.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('JW301', '0100', '0041', '0530', 'Toewijzing Jeugd', 'GDK', 'Inlichtingenbureau', 'GDK', 'Beheer_GDK', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'autorisatie', '041.530.01', 'N2014-139');
INSERT INTO "public"."uitwisselingen" VALUES ('JW301', '0100', '0050', '0041', 'Toewijzing Jeugd', 'Zorgverzekeraars', 'Inlichtingenbureau', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'Zorgverzekeraars', 'Beheer_VECOZO', 'autorisatie', '050.041.03', 'N2013-139');
INSERT INTO "public"."uitwisselingen" VALUES ('WMO303', '0100', '0530', '0041', 'Declaratie WMO', 'GDK', 'Inlichtingenbureau', 'Inlichtingenbureau', 'Beheer_VECOZO', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'autorisatie', '530.041.04', 'N2014-139');
INSERT INTO "public"."uitwisselingen" VALUES ('JW303', '0100', '0041', '0050', 'Declaratie Jeugd-AWBZ', 'Inlichtingenbureau', 'Zorgverzekeraars', 'Zorgverzekeraars', 'Beheer_Inlichtingenbureau', 'Inlichtingenbureau', 'Beheer_VECOZO', 'autorisatie', '041.050.02', 'N2013-139');
INSERT INTO "public"."uitwisselingen" VALUES ('JW303', '0100', '0530', '0041', 'Declaratie Jeugd-AWBZ', 'GDK', 'Inlichtingenbureau', 'Inlichtingenbureau', 'Beheer_VECOZO', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'autorisatie', '530.041.02', 'N2014-139');
INSERT INTO "public"."uitwisselingen" VALUES ('FO01', '0100', '0041', '0050', 'Foutberichten IB', 'Inlichtingenbureau', 'Vecozo', 'Inlichtingenbureau', 'Beheer_VECOZO', 'Zorgverzekeraars', 'Beheer_Inlichtingenbureau', 'autorisatie', '041.050.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('346', '001', '0110', '0120', 'Onderwijs', 'DUO', 'CBS', 'DUO', 'Beheer_DUO', 'CBS', 'Beheer_CBS', 'autorisatie', '110.120.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('014', '001', '0050', '0030', 'Wanbetalers', 'Zorgverzekeraars', 'SVB', 'SVB', 'Beheer_SVB', 'Zorgverzekeraars', 'Beheer_ZORG', 'vervallen autorisatie', '050.030.03', null);
INSERT INTO "public"."uitwisselingen" VALUES ('406', '100', '0050', '0020', 'Loonbeslag wanbetalers', 'CVZ', 'UWV', 'CVZ', 'Beheer_CVZ', 'UWV', 'Beheer_UWV', 'vervallen autorisatie', '050.020.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('360', '001', '0050', '0030', 'Wanbetalers', 'Zorgverzekeraars', 'SVB', 'Zorgverzekeraars', 'Beheer_ZORG', 'SVB', 'Beheer_SVB', 'vervallen autorisatie', '050.030.03', null);
INSERT INTO "public"."uitwisselingen" VALUES ('406', '060', '0050', '0020', 'Loonbeslag wanbetalers', 'Zorgverzekeraars', 'UWV', 'Zorgverzekeraars', 'Beheer_Zorginstituut Nederland', 'UWV', 'Beheer_UWV', 'vervallen autorisatie', '050.020.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('406', '004', '0050', '0020', 'Loonbeslag wanbetalers', 'Zorgverzekeraars', 'UWV', 'Zorgverzekeraars', 'Beheer_Zorginstituut Nederland', 'UWV', 'Beheer_UWV', 'vervallen autorisatie', '050.020.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('407', '004', '0050', '0020', 'Loonbeslag wanbetalers', 'Zorgverzekeraars', 'UWV', 'Zorgverzekeraars', 'Beheer_Zorginstituut Nederland', 'UWV', 'Beheer_UWV', 'vervallen autorisatie', '050.020.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('407', '060', '0050', '0020', 'Loonbeslag wanbetalers', 'Zorgverzekeraars', 'UWV', 'Zorgverzekeraars', 'Beheer_Zorginstituut Nederland', 'UWV', 'Beheer_UWV', 'vervallen autorisatie', '050.020.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('408', '002', '0050', '0020', 'Loonbeslag wanbetalers', 'Zorgverzekeraars', 'UWV', 'UWV', 'Beheer_UWV', 'Zorgverzekeraars', 'Beheer_Zorginstituut Nederland', 'vervallen autorisatie', '050.020.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('407', '100', '0050', '0020', 'Loonbeslag wanbetalers', 'CVZ', 'UWV', 'CVZ', 'Beheer_CVZ', 'UWV', 'Beheer_UWV', 'vervallen autorisatie', '050.020.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('901', '002', '0020', '0030', 'Inkomstenverhoudingen', 'UWV', 'SVB', 'UWV', 'Beheer_UWV', 'SVB', 'Beheer_SVB', 'vervallen autorisatie', null, null);
INSERT INTO "public"."uitwisselingen" VALUES ('902', '002', '0020', '0030', 'Inkomstenverhoudingen', 'UWV', 'SVB', 'UWV', 'Beheer_UWV', 'SVB', 'Beheer_SVB', 'vervallen autorisatie', null, null);
INSERT INTO "public"."uitwisselingen" VALUES ('951', '002', '0020', '0030', 'Inkomstenverhoudingen', 'UWV', 'SVB', 'UWV', 'Beheer_UWV', 'SVB', 'Beheer_SVB', 'vervallen autorisatie', null, null);
INSERT INTO "public"."uitwisselingen" VALUES ('408', '060', '0050', '0020', 'Loonbeslag wanbetalers', 'CVZ', 'UWV', 'UWV', 'Beheer_UWV', 'CVZ', 'Beheer_CVZ', 'vervallen autorisatie', '050.020.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('351', '001', '0050', '0030', 'Broninhouding wanbetalers', 'Zorgverzekeraars', 'SVB', 'Zorgverzekeraars', 'Beheer_Zorginstituut Nederland', 'SVB', 'Beheer_SVB', 'vervallen autorisatie', '050.030.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('352', '001', '0050', '0030', 'Broninhouding wanbetalers', 'Zorgverzekeraars', 'SVB', 'Zorgverzekeraars', 'Beheer_Zorginstituut Nederland', 'SVB', 'Beheer_SVB', 'vervallen autorisatie', '050.030.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('372', '001', '0110', '0070', 'Landelijke Registratie Kinderopvang', 'DUO', 'Belastingdienst', 'DUO', 'Beheer_DUO_LRK', 'Belastingdienst', 'Beheer_BD_Incidenten', 'vervallen autorisatie', '110.070.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('326', '001', '0030', '0050', 'Gemoedsbezwaarden', 'SVB', 'Zorgverzekeraars', 'SVB', 'Beheer_SVB', 'Zorgverzekeraars', 'Beheer_ZORG', 'vervallen autorisatie', '030.050.02', null);
INSERT INTO "public"."uitwisselingen" VALUES ('400', '211', '0020', '0140', 'Inkomstenverhoudingen', 'UWV', 'CAK', 'CAK', 'Beheer_CAK', 'UWV', 'Beheer_UWV', 'vervallen autorisatie', '020.140.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('400', '211', '0020', '0050', 'Inkomstenverhoudingen', 'UWV', 'CVZ', 'CVZ', 'Beheer_CVZ', 'UWV', 'Beheer_UWV', 'vervallen autorisatie', null, null);
INSERT INTO "public"."uitwisselingen" VALUES ('373', '001', '0050', '0060', 'Wanbetalers', 'CVZ', 'CJIB', 'CVZ', 'Beheer_CVZ', 'CJIB', 'Beheer_CJIB', 'vervallen autorisatie', null, null);
INSERT INTO "public"."uitwisselingen" VALUES ('401', '201', '0020', '0050', 'Inkomstenverhoudingen', 'UWV', 'CVZ', 'UWV', 'Beheer_UWV', 'CVZ', 'Beheer_CVZ', 'vervallen autorisatie', null, null);
INSERT INTO "public"."uitwisselingen" VALUES ('490', '221', '0020', '0050', 'Inkomstenverhoudingen', 'UWV', 'CVZ', 'UWV', 'Beheer_UWV', 'CVZ', 'Beheer_CVZ', 'vervallen autorisatie', null, 'N22, N10');
INSERT INTO "public"."uitwisselingen" VALUES ('480', '151', '0020', '0140', 'Inkomstenverhoudingen', 'UWV', 'CAK', 'UWV', 'Beheer_UWV', 'CAK', 'Beheer_CAK', 'vervallen autorisatie', '020.140.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('480', '181', '0020', '0140', 'Inkomstenverhoudingen', 'UWV', 'CAK', 'UWV', 'Beheer_UWV', 'CAK', 'Beheer_CAK', 'vervallen autorisatie', '020.140.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('401', '201', '0020', '0140', 'Inkomstenverhoudingen', 'UWV', 'CAK', 'UWV', 'Beheer_UWV', 'CAK', 'Beheer_CAK', 'vervallen autorisatie', '020.140.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('372', '001', '0510', '0070', 'Landelijke Registratie Kinderopvang', 'Digikoppeling / DUO', 'Belastingdienst', 'Digikoppeling / DUO', 'Beheer_DUO_LRK', 'Belastingdienst', 'Beheer_BD_Incidenten', 'vervallen autorisatie', '510.070.02', 'N39');
INSERT INTO "public"."uitwisselingen" VALUES ('353', '001', '0050', '0030', 'Broninhouding wanbetalers', 'Zorgverzekeraars', 'SVB', 'SVB', 'Beheer_SVB', 'Zorgverzekeraars', 'Beheer_Zorginstituut Nederland', 'vervallen autorisatie', '050.030.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('354', '001', '0050', '0030', 'Broninhouding wanbetalers', 'Zorgverzekeraars', 'SVB', 'SVB', 'Beheer_SVB', 'Zorgverzekeraars', 'Beheer_Zorginstituut Nederland', 'vervallen autorisatie', '050.030.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('375', '001', '0050', '0060', 'Wanbetalers', 'CVZ', 'CJIB', 'CJIB', 'Beheer_CJIB', 'CVZ', 'Beheer_CVZ', 'vervallen autorisatie', null, null);
INSERT INTO "public"."uitwisselingen" VALUES ('374', '002', '0050', '0060', 'Wanbetalers', 'CVZ', 'CJIB', 'CJIB', 'Beheer_CJIB', 'CVZ', 'Beheer_CVZ', 'vervallen autorisatie', null, null);
INSERT INTO "public"."uitwisselingen" VALUES ('374', '001', '0050', '0060', 'Wanbetalers', 'CVZ', 'CJIB', 'CJIB', 'Beheer_CJIB', 'CVZ', 'Beheer_CVZ', 'vervallen autorisatie', null, null);
INSERT INTO "public"."uitwisselingen" VALUES ('651', '116', '0101', '0041', 'SUWI 2', 'CWI', 'Inlichtingenbureau', 'CWI', 'Beheer_CWI', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'vervallen autorisatie', null, null);
INSERT INTO "public"."uitwisselingen" VALUES ('653', '101', '0101', '0041', 'SUWI 2', 'CWI', 'Inlichtingenbureau', 'CWI', 'Beheer_CWI', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'vervallen autorisatie', null, null);
INSERT INTO "public"."uitwisselingen" VALUES ('654', '101', '0101', '0041', 'SUWI 2', 'CWI', 'Inlichtingenbureau', 'CWI', 'Beheer_CWI', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'vervallen autorisatie', null, null);
INSERT INTO "public"."uitwisselingen" VALUES ('656', '102', '0101', '0041', 'SUWI 2', 'CWI', 'Inlichtingenbureau', 'CWI', 'Beheer_CWI', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'vervallen autorisatie', null, null);
INSERT INTO "public"."uitwisselingen" VALUES ('657', '133', '0101', '0041', 'SUWI 2', 'CWI', 'Inlichtingenbureau', 'CWI', 'Beheer_CWI', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'vervallen autorisatie', null, null);
INSERT INTO "public"."uitwisselingen" VALUES ('658', '103', '0101', '0041', 'SUWI 2', 'CWI', 'Inlichtingenbureau', 'CWI', 'Beheer_CWI', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'vervallen autorisatie', null, null);
INSERT INTO "public"."uitwisselingen" VALUES ('652', '101', '0041', '0101', 'SUWI 2', 'Inlichtingenbureau', 'CWI', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'CWI', 'Beheer_CWI', 'vervallen autorisatie', null, null);
INSERT INTO "public"."uitwisselingen" VALUES ('655', '100', '0041', '0101', 'SUWI 2', 'Inlichtingenbureau', 'CWI', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'CWI', 'Beheer_CWI', 'vervallen autorisatie', null, null);
INSERT INTO "public"."uitwisselingen" VALUES ('659', '101', '0041', '0101', 'SUWI 2', 'Inlichtingenbureau', 'CWI', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'CWI', 'Beheer_CWI', 'vervallen autorisatie', null, null);
INSERT INTO "public"."uitwisselingen" VALUES ('660', '101', '0041', '0101', 'SUWI 2', 'Inlichtingenbureau', 'CWI', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'CWI', 'Beheer_CWI', 'vervallen autorisatie', null, null);
INSERT INTO "public"."uitwisselingen" VALUES ('661', '102', '0041', '0101', 'SUWI 2', 'Inlichtingenbureau', 'CWI', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'CWI', 'Beheer_CWI', 'vervallen autorisatie', null, null);
INSERT INTO "public"."uitwisselingen" VALUES ('662', '102', '0041', '0101', 'SUWI 2', 'Inlichtingenbureau', 'CWI', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'CWI', 'Beheer_CWI', 'vervallen autorisatie', null, null);
INSERT INTO "public"."uitwisselingen" VALUES ('303', '002', '0020', '0030', 'Inkomstenverhoudingen', 'UWV', 'SVB', 'UWV', 'Beheer_UWV', 'SVB', 'Beheer_SVB', 'vervallen autorisatie', null, null);
INSERT INTO "public"."uitwisselingen" VALUES ('323', '001', '0101', '0120', 'Werkzoekenden', 'CWI', 'CBS', 'CWI', 'Beheer_CWI', 'CBS', 'Beheer_CBS', 'vervallen autorisatie', null, null);
INSERT INTO "public"."uitwisselingen" VALUES ('314', '001', '0055', '0030', 'Persoonsgebonden budget', 'Ziektekostenverzekeraars (PGB)', 'SVB', 'Ziektekostenverzekeraars (PGB)', 'Beheer_PGB', 'SVB', 'Beheer_SVB', 'vervallen autorisatie', null, null);
INSERT INTO "public"."uitwisselingen" VALUES ('762', '001', '0101', '0120', 'Grote berichten', 'CWI', 'CBS', 'CWI', 'Beheer_CWI', 'CBS', 'Beheer_CBS', 'vervallen autorisatie', null, null);
INSERT INTO "public"."uitwisselingen" VALUES ('308', '001', '0030', '0050', 'Inkomstenverhoudingen', 'SVB', 'Zorgverzekeraars', 'SVB', 'Beheer_SVB', 'Zorgverzekeraars', 'Beheer_ZORG', 'vervallen autorisatie', null, null);
INSERT INTO "public"."uitwisselingen" VALUES ('309', '001', '0030', '0050', 'Inkomstenverhoudingen', 'SVB', 'Zorgverzekeraars', 'SVB', 'Beheer_SVB', 'Zorgverzekeraars', 'Beheer_ZORG', 'vervallen autorisatie', null, null);
INSERT INTO "public"."uitwisselingen" VALUES ('001', '002', '0020', '0050', 'Inkomstenverhoudingen', 'UWV', 'Zorgverzekeraars', 'Zorgverzekeraars', 'Beheer_ZORG', 'UWV', 'Beheer_UWV', 'vervallen autorisatie', null, null);
INSERT INTO "public"."uitwisselingen" VALUES ('342', '001', '0030', '0120', 'AOW- en Anw-gerechtigden', 'SVB', 'CBS', 'SVB', 'Beheer_SVB', 'CBS', 'Beheer_CBS', 'vervallen autorisatie', '030.120.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('901', '002', '0020', '0041', 'Inkomstenverhoudingen', 'UWV', 'Inlichtingenbureau', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'UWV', 'Beheer_UWV', 'vervallen autorisatie', null, null);
INSERT INTO "public"."uitwisselingen" VALUES ('727', '001', '0050', '0150', 'Buitenland declaraties', 'Zorgverzekeraars', 'ZINL', 'Zorgverzekeraars', 'Beheer_VECOZO', 'ZINL', 'Beheer_Zorginstituut Nederland', 'autorisatie', '050.150.02', null);
INSERT INTO "public"."uitwisselingen" VALUES ('726', '001', '0050', '0150', 'Buitenland declaraties', 'Zorgverzekeraars', 'ZINL', 'ZINL', 'Beheer_Zorginstituut Nederland', 'Zorgverzekeraars', 'Beheer_VECOZO', 'autorisatie', '050.150.02', null);
INSERT INTO "public"."uitwisselingen" VALUES ('605', '001', '0050', '0041', 'Onverzekerden en wanbetalers', 'Zorgverzekeraars', 'Inlichtingenbureau', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'Zorgverzekeraars', 'Beheer_ZORG', 'vervallen autorisatie', null, null);
INSERT INTO "public"."uitwisselingen" VALUES ('902', '002', '0020', '0041', 'Inkomstenverhoudingen', 'UWV', 'Inlichtingenbureau', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'UWV', 'Beheer_UWV', 'vervallen autorisatie', null, null);
INSERT INTO "public"."uitwisselingen" VALUES ('306', '001', '0061', '0041', 'Detentie', 'DJI', 'Inlichtingenbureau', 'DJI', 'Beheer_DJI', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'vervallen autorisatie', '061.041.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('666', '111', '0101', '0041', 'SUWI 3', 'CWI', 'Inlichtingenbureau', 'CWI', 'Beheer_CWI', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'vervallen autorisatie', null, null);
INSERT INTO "public"."uitwisselingen" VALUES ('664', '102', '0101', '0041', 'SUWI 3', 'CWI', 'Inlichtingenbureau', 'CWI', 'Beheer_CWI', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'vervallen autorisatie', null, null);
INSERT INTO "public"."uitwisselingen" VALUES ('666', '103', '0101', '0041', 'SUWI 3', 'CWI', 'Inlichtingenbureau', 'CWI', 'Beheer_CWI', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'vervallen autorisatie', null, null);
INSERT INTO "public"."uitwisselingen" VALUES ('665', '102', '0101', '0041', 'SUWI 3', 'CWI', 'Inlichtingenbureau', 'CWI', 'Beheer_CWI', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'vervallen autorisatie', null, null);
INSERT INTO "public"."uitwisselingen" VALUES ('663', '103', '0101', '0041', 'SUWI 3', 'CWI', 'Inlichtingenbureau', 'CWI', 'Beheer_CWI', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'vervallen autorisatie', null, null);
INSERT INTO "public"."uitwisselingen" VALUES ('667', '102', '0101', '0041', 'SUWI 3', 'CWI', 'Inlichtingenbureau', 'CWI', 'Beheer_CWI', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'vervallen autorisatie', null, null);
INSERT INTO "public"."uitwisselingen" VALUES ('668', '102', '0101', '0041', 'SUWI 3', 'CWI', 'Inlichtingenbureau', 'CWI', 'Beheer_CWI', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'vervallen autorisatie', null, null);
INSERT INTO "public"."uitwisselingen" VALUES ('310', '002', '0020', '0030', 'Inkomstenverhoudingen', 'UWV', 'SVB', 'UWV', 'Beheer_UWV', 'SVB', 'Beheer_SVB', 'vervallen autorisatie', null, null);
INSERT INTO "public"."uitwisselingen" VALUES ('951', '002', '0020', '0041', 'Inkomstenverhoudingen', 'UWV', 'Inlichtingenbureau', 'UWV', 'Beheer_UWV', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'vervallen autorisatie', null, null);
INSERT INTO "public"."uitwisselingen" VALUES ('760', '001', '0101', '0070', 'DVD uitwisseling (K156B)', 'CWI', 'Belastingdienst', 'CWI', 'Beheer_CWI', 'Belastingdienst', 'Beheer_BD_Incidenten', 'vervallen autorisatie', null, null);
INSERT INTO "public"."uitwisselingen" VALUES ('304', '004', '0020', '0041', 'Inkomstenverhoudingen', 'UWV', 'Inlichtingenbureau', 'UWV', 'Beheer_UWV', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'vervallen autorisatie', null, null);
INSERT INTO "public"."uitwisselingen" VALUES ('337', '001', '0030', '0070', 'Kindertoeslag', 'SVB', 'Belastingdienst', 'SVB', 'Beheer_SVB', 'Belastingdienst', 'Beheer_BD_Incidenten', 'vervallen autorisatie', '030.070.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('339', '001', '0030', '0070', 'Kindertoeslag', 'SVB', 'Belastingdienst', 'SVB', 'Beheer_SVB', 'Belastingdienst', 'Beheer_BD_Incidenten', 'vervallen autorisatie', '030.070.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('336', '001', '0030', '0070', 'Kindertoeslag', 'SVB', 'Belastingdienst', 'SVB', 'Beheer_SVB', 'Belastingdienst', 'Beheer_BD_Incidenten', 'vervallen autorisatie', '030.070.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('340', '001', '0030', '0070', 'Kindertoeslag', 'SVB', 'Belastingdienst', 'SVB', 'Beheer_SVB', 'Belastingdienst', 'Beheer_BD_Incidenten', 'vervallen autorisatie', '030.070.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('001', '002', '0020', '0060', 'Inkomstenverhoudingen', 'UWV', 'LBIO', 'LBIO', 'Beheer_LBIO', 'UWV', 'Beheer_UWV', 'vervallen autorisatie', null, null);
INSERT INTO "public"."uitwisselingen" VALUES ('001', '002', '0030', '0050', 'Ziekenfondsrecht', 'SVB', 'Zorgverzekeraars', 'Zorgverzekeraars', 'Beheer_ZORG', 'SVB', 'Beheer_SVB', 'vervallen autorisatie', null, null);
INSERT INTO "public"."uitwisselingen" VALUES ('302', '002', '0020', '0041', 'Inkomstenverhoudingen', 'UWV', 'Inlichtingenbureau', 'UWV', 'Beheer_UWV', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'vervallen autorisatie', null, null);
INSERT INTO "public"."uitwisselingen" VALUES ('305', '003', '0020', '0060', 'Inkomstenverhoudingen', 'UWV', 'LBIO', 'UWV', 'Beheer_UWV', 'LBIO', 'Beheer_LBIO', 'vervallen autorisatie', null, null);
INSERT INTO "public"."uitwisselingen" VALUES ('308', '001', '0020', '0050', 'Ziekenfondsrecht', 'UWV', 'Zorgverzekeraars', 'UWV', 'Beheer_UWV', 'Zorgverzekeraars', 'Beheer_ZORG', 'vervallen autorisatie', null, null);
INSERT INTO "public"."uitwisselingen" VALUES ('309', '001', '0020', '0050', 'Ziekenfondsrecht', 'UWV', 'Zorgverzekeraars', 'UWV', 'Beheer_UWV', 'Zorgverzekeraars', 'Beheer_ZORG', 'vervallen autorisatie', null, null);
INSERT INTO "public"."uitwisselingen" VALUES ('312', '003', '0020', '0060', 'Inkomstenverhoudingen', 'UWV', 'LBIO', 'UWV', 'Beheer_UWV', 'LBIO', 'Beheer_LBIO', 'vervallen autorisatie', null, null);
INSERT INTO "public"."uitwisselingen" VALUES ('006', '001', '0050', '0030', 'AOW-informatie', 'Zorgverzekeraars', 'SVB', 'SVB', 'Beheer_SVB', 'Zorgverzekeraars', 'Beheer_ZORG', 'vervallen autorisatie', null, null);
INSERT INTO "public"."uitwisselingen" VALUES ('001', '002', '0020', '0030', 'Inkomstenverhoudingen', 'UWV', 'SVB', 'SVB', 'Beheer_SVB', 'UWV', 'Beheer_UWV', 'vervallen autorisatie', null, null);
INSERT INTO "public"."uitwisselingen" VALUES ('901', '002', '0020', '0060', 'Inkomstenverhoudingen', 'UWV', 'LBIO', 'UWV', 'Beheer_UWV', 'LBIO', 'Beheer_LBIO', 'vervallen autorisatie', null, null);
INSERT INTO "public"."uitwisselingen" VALUES ('902', '002', '0020', '0060', 'Inkomstenverhoudingen', 'UWV', 'LBIO', 'UWV', 'Beheer_UWV', 'LBIO', 'Beheer_LBIO', 'vervallen autorisatie', null, null);
INSERT INTO "public"."uitwisselingen" VALUES ('951', '002', '0020', '0060', 'Inkomstenverhoudingen', 'UWV', 'LBIO', 'UWV', 'Beheer_UWV', 'LBIO', 'Beheer_LBIO', 'vervallen autorisatie', null, null);
INSERT INTO "public"."uitwisselingen" VALUES ('661', '123', '0041', '0101', 'SUWI 2', 'Inlichtingenbureau', 'CWI', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'CWI', 'Beheer_CWI', 'vervallen autorisatie', null, null);
INSERT INTO "public"."uitwisselingen" VALUES ('319', '001', '0050', '0030', 'Levering AOW', 'Zorgverzekeraars', 'SVB', 'Zorgverzekeraars', 'Beheer_ZORG', 'SVB', 'Beheer_SVB', 'vervallen autorisatie', null, null);
INSERT INTO "public"."uitwisselingen" VALUES ('400', '145', '0020', '0050', 'Inkomstenverhoudingen', 'UWV', 'CVZ', 'CVZ', 'Beheer_CVZ', 'UWV', 'Beheer_UWV', 'vervallen autorisatie', null, null);
INSERT INTO "public"."uitwisselingen" VALUES ('004', '001', '0030', '0055', 'Persoonsgebonden budget', 'SVB', 'Ziektekostenverzekeraars (PGB)', 'SVB', 'Beheer_SVB', 'Ziektekostenverzekeraars (PGB)', 'Beheer_PGB', 'vervallen autorisatie', null, null);
INSERT INTO "public"."uitwisselingen" VALUES ('001', '002', '0020', '0041', 'Inkomstenverhoudingen', 'UWV', 'Inlichtingenbureau', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'UWV', 'Beheer_UWV', 'vervallen autorisatie', null, null);
INSERT INTO "public"."uitwisselingen" VALUES ('304', '003', '0020', '0041', 'Inkomstenverhoudingen', 'UWV', 'Inlichtingenbureau', 'UWV', 'Beheer_UWV', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'vervallen autorisatie', null, null);
INSERT INTO "public"."uitwisselingen" VALUES ('313', '001', '0030', '0055', 'Persoonsgebonden budget', 'SVB', 'Ziektekostenverzekeraars (PGB)', 'Ziektekostenverzekeraars (PGB)', 'Beheer_PGB', 'SVB', 'Beheer_SVB', 'vervallen autorisatie', null, null);
INSERT INTO "public"."uitwisselingen" VALUES ('608', '001', '0030', '0510', 'Berichtenbox RDW', 'SVB', 'Digikoppeling / RDW', 'SVB', 'Beheer_SVB_MijnOverheid', 'Digikoppeling / RDW', 'Beheer_MijnOverheid_Berichtenbox', 'vervallen autorisatie', null, null);
INSERT INTO "public"."uitwisselingen" VALUES ('602', '104', '0070', '0062', 'Inkomensgegevens', 'Belastingdienst', 'Raad voor Rechtsbijstand', 'Belastingdienst', 'Beheer_BD_Incidenten', 'Raad voor Rechtsbijstand', 'Beheer_RVR', 'vervallen autorisatie', null, null);
INSERT INTO "public"."uitwisselingen" VALUES ('400', '145', '0020', '0060', 'Inkomstenverhoudingen', 'UWV', 'LBIO', 'LBIO', 'Beheer_LBIO', 'UWV', 'Beheer_UWV', 'vervallen autorisatie', '020.060.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('423', '221', '0020', '0060', 'Inkomstenverhoudingen', 'UWV', 'LBIO', 'UWV', 'Beheer_UWV', 'LBIO', 'Beheer_LBIO', 'vervallen autorisatie', '020.060.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('401', '151', '0020', '0060', 'Inkomstenverhoudingen', 'UWV', 'LBIO', 'UWV', 'Beheer_UWV', 'LBIO', 'Beheer_LBIO', 'vervallen autorisatie', '020.060.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('320', '001', '0030', '0041', 'AOW-informatie', 'SVB', 'Inlichtingenbureau', 'SVB', 'Beheer_SVB', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'vervallen autorisatie', null, null);
INSERT INTO "public"."uitwisselingen" VALUES ('700', '001', '0130', '0120', 'Bloemenstatistiek en EGS-POS', 'Digipoort', 'CBS', 'Digipoort', 'Beheer_OTP', 'CBS', 'Beheer_CBS', 'vervallen autorisatie', '130.120.02', null);
INSERT INTO "public"."uitwisselingen" VALUES ('701', '001', '0130', '0120', 'Bloemenstatistiek en EGS-POS', 'Digipoort', 'CBS', 'Digipoort', 'Beheer_OTP', 'CBS', 'Beheer_CBS', 'vervallen autorisatie', '130.120.02', null);
INSERT INTO "public"."uitwisselingen" VALUES ('356', '001', '0110', '0030', '16- en 17-jarigen met een startkwalificatie of praktijkovereenkomst', 'DUO', 'SVB', 'DUO', 'Beheer_DUO', 'SVB', 'Beheer_SVB', 'autorisatie', '110.030.03', null);
INSERT INTO "public"."uitwisselingen" VALUES ('357', '001', '0110', '0030', '16- en 17-jarigen met een startkwalificatie of praktijkovereenkomst', 'DUO', 'SVB', 'DUO', 'Beheer_DUO', 'SVB', 'Beheer_SVB', 'autorisatie', '110.030.03', null);
INSERT INTO "public"."uitwisselingen" VALUES ('016', '001', '0110', '0030', 'AKW in relatie met studie', 'DUO', 'SVB', 'SVB', 'Beheer_SVB', 'DUO', 'Beheer_DUO', 'autorisatie', '110.030.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('381', '001', '0150', '0050', 'Ambtshalve verzekerden', 'ZINL', 'Zorgverzekeraars', 'ZINL', 'Beheer_Zorginstituut Nederland', 'Zorgverzekeraars', 'Beheer_VECOZO', 'autorisatie', '150.050.02', null);
INSERT INTO "public"."uitwisselingen" VALUES ('365', '001', '0110', '0030', 'AKW in relatie met studie', 'DUO', 'SVB', 'DUO', 'Beheer_DUO', 'SVB', 'Beheer_SVB', 'autorisatie', '110.030.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('320', '002', '0030', '0041', 'AOW-, Anw- en WWB65plus-informatie', 'SVB', 'Inlichtingenbureau', 'SVB', 'Beheer_SVB', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'autorisatie', '030.041.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('728', '001', '0140', '0120', 'WTCG', 'CAK', 'CBS', 'CAK', 'Beheer_CAK', 'CBS', 'Beheer_CBS', 'autorisatie', '140.120.01', 'N2012-4');
INSERT INTO "public"."uitwisselingen" VALUES ('321', '001', '0030', '0041', 'AOW-, Anw- en WWB65plus-informatie', 'SVB', 'Inlichtingenbureau', 'SVB', 'Beheer_SVB', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'autorisatie', '030.041.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('612', '001', '0510', '0030', 'Abonnementenservice Berichtenbox', 'Digikoppeling / RDW', 'SVB', 'SVB', 'Beheer_SVB_MijnOverheid', 'Digikoppeling / RDW', 'Beheer_MijnOverheid_Berichtenbox', 'autorisatie', '510.030.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('325', '001', '0030', '0041', 'AOW-, Anw- en WWB65plus-informatie', 'SVB', 'Inlichtingenbureau', 'SVB', 'Beheer_SVB', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'autorisatie', '030.041.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('342', '002', '0030', '0120', 'AOW- en Anw-gerechtigden', 'SVB', 'CBS', 'SVB', 'Beheer_SVB', 'CBS', 'Beheer_CBS', 'autorisatie', '030.120.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('351', '002', '0150', '0030', 'Broninhouding wanbetalers', 'ZINL', 'SVB', 'ZINL', 'Beheer_Zorginstituut Nederland', 'SVB', 'Beheer_SVB', 'autorisatie', '150.030.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('352', '002', '0150', '0030', 'Broninhouding wanbetalers', 'ZINL', 'SVB', 'ZINL', 'Beheer_Zorginstituut Nederland', 'SVB', 'Beheer_SVB', 'autorisatie', '150.030.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('737', '001', '0510', '0070', 'Wijziging Uitvoering Registratiewet 1970 (WUR)', 'Digikoppeling / KNB', 'Belastingdienst', 'Belastingdienst', 'Beheer_BD_Incidenten', 'Digikoppeling / KNB', 'Beheer_KNB', 'autorisatie', '510.070.04', 'N15');
INSERT INTO "public"."uitwisselingen" VALUES ('735', '001', '0070', '0140', 'NINBI/WTCG/AIG', 'Belastingdienst', 'CAK', 'Belastingdienst', 'Beheer_BD_Incidenten', 'CAK', 'Beheer_CAK', 'autorisatie', '070.140.01', 'N3');
INSERT INTO "public"."uitwisselingen" VALUES ('613', '001', '0510', '0030', 'Abonnementenservice Berichtenbox', 'Digikoppeling / RDW', 'SVB', 'Digikoppeling / RDW', 'Beheer_MijnOverheid_Berichtenbox', 'SVB', 'Beheer_SVB_MijnOverheid', 'autorisatie', '510.030.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('732', '001', '0140', '0120', 'WTCG', 'CAK', 'CBS', 'CAK', 'Beheer_CAK', 'CBS', 'Beheer_CBS', 'autorisatie', '140.120.01', 'N2012-4');
INSERT INTO "public"."uitwisselingen" VALUES ('729', '001', '0140', '0120', 'WTCG', 'CAK', 'CBS', 'CAK', 'Beheer_CAK', 'CBS', 'Beheer_CBS', 'autorisatie', '140.120.01', 'N2012-4');
INSERT INTO "public"."uitwisselingen" VALUES ('730', '001', '0140', '0120', 'WTCG', 'CAK', 'CBS', 'CAK', 'Beheer_CAK', 'CBS', 'Beheer_CBS', 'autorisatie', '140.120.01', 'N2012-4');
INSERT INTO "public"."uitwisselingen" VALUES ('731', '001', '0140', '0120', 'WTCG', 'CAK', 'CBS', 'CAK', 'Beheer_CAK', 'CBS', 'Beheer_CBS', 'autorisatie', '140.120.01', 'N2012-4');
INSERT INTO "public"."uitwisselingen" VALUES ('610', '001', '0030', '0510', 'Berichtenbox RDW', 'SVB', 'Digikoppeling / RDW', 'SVB', 'Beheer_SVB_MijnOverheid', 'Digikoppeling / RDW', 'Beheer_MijnOverheid_Berichtenbox', 'vervallen autorisatie', '030.510.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('611', '001', '0030', '0510', 'Berichtenbox RDW', 'SVB', 'Digikoppeling / RDW', 'Digikoppeling / RDW', 'Beheer_MijnOverheid_Berichtenbox', 'SVB', 'Beheer_SVB_MijnOverheid', 'vervallen autorisatie', '030.510.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('327', '001', '0030', '0120', 'AOW- en Anw-gerechtigden', 'SVB', 'CBS', 'SVB', 'Beheer_SVB', 'CBS', 'Beheer_CBS', 'vervallen autorisatie', '030.120.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('384', '100', '0150', '0050', 'Afslag bestand CVZ-Verzekerden', 'ZINL', 'Zorgverzekeraars', 'ZINL', 'Beheer_Zorginstituut Nederland', 'Zorgverzekeraars', 'Beheer_VECOZO', 'autorisatie', '150.050.01', 'N2');
INSERT INTO "public"."uitwisselingen" VALUES ('389', '001', '0510', '0070', 'Wijziging Uitvoering Registratiewet 1970 (WUR)', 'Digikoppeling / KNB', 'Belastingdienst', 'Digikoppeling / KNB', 'Beheer_KNB', 'Belastingdienst', 'Beheer_BD_Incidenten', 'autorisatie', '510.070.04', 'N15');
INSERT INTO "public"."uitwisselingen" VALUES ('736', '001', '0510', '0070', 'Wijziging Uitvoering Registratiewet 1970 (WUR)', 'Digikoppeling / KNB', 'Belastingdienst', 'Digikoppeling / KNB', 'Beheer_KNB', 'Belastingdienst', 'Beheer_BD_Incidenten', 'autorisatie', '510.070.04', 'N15');
INSERT INTO "public"."uitwisselingen" VALUES ('734', '001', '0070', '0140', 'NINBI/WTCG/AIG', 'Belastingdienst', 'CAK', 'CAK', 'Beheer_CAK', 'Belastingdienst', 'Beheer_BD_Incidenten', 'autorisatie', '070.140.01', 'N3');
INSERT INTO "public"."uitwisselingen" VALUES ('382', '001', '0150', '0050', 'Ambtshalve verzekerden', 'ZINL', 'Zorgverzekeraars', 'Zorgverzekeraars', 'Beheer_VECOZO', 'ZINL', 'Beheer_Zorginstituut Nederland', 'autorisatie', '150.050.02', null);
INSERT INTO "public"."uitwisselingen" VALUES ('003', '003', '0070', '0050', 'Identificatie en verificatie van sofinummers (IVP)', 'Belastingdienst', 'Zorgverzekeraars', 'Zorgverzekeraars', 'Beheer_VECOZO', 'Belastingdienst', 'Beheer_BD_Incidenten', 'vervallen autorisatie', '070.050.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('705', '001', '0070', '0130', 'BTW refund', 'Belastingdienst', 'Digipoort', 'Digipoort', 'Beheer_OTP', 'Belastingdienst', 'Beheer_BD_Incidenten', 'autorisatie', '070.130.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('760', '001', '0020', '0070', 'DVD uitwisseling (K156B)', 'UWV', 'Belastingdienst', 'UWV', 'Beheer_UWV', 'Belastingdienst', 'Beheer_BD_Incidenten', 'autorisatie', '020.070.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('003', '003', '0070', '0030', 'Identificatie en verificatie van sofinummers (IVP)', 'Belastingdienst', 'SVB', 'SVB', 'Beheer_SVB', 'Belastingdienst', 'Beheer_BD_Incidenten', 'autorisatie', '070.030.03', null);
INSERT INTO "public"."uitwisselingen" VALUES ('353', '002', '0050', '0030', 'Broninhouding wanbetalers', 'Zorgverzekeraars', 'SVB', 'SVB', 'Beheer_SVB', 'Zorgverzekeraars', 'Beheer_Zorginstituut Nederland', 'autorisatie', '050.030.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('720', '001', '0510', '0070', 'eFactureren', 'Digikoppeling / Digipoort', 'Belastingdienst', 'Belastingdienst', 'Beheer_BD_Incidenten', 'Digikoppeling / Digipoort', 'Beheer_???', 'autorisatie', '510.070.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('306', '002', '0061', '0041', 'Detentie', 'DJI', 'Inlichtingenbureau', 'DJI', 'Beheer_DJI', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'autorisatie', '061.041.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('712', '001', '0510', '0070', 'eMededelen', 'Digikoppeling / RDW', 'Belastingdienst', 'Digikoppeling / RDW', 'Beheer_MijnOverheid_Berichtenbox', 'Belastingdienst', 'Beheer_BD_Incidenten', 'vervallen autorisatie', '510.070.03', 'N9');
INSERT INTO "public"."uitwisselingen" VALUES ('001', '002', '0020', '0080', 'Inkomstenverhoudingen', 'UWV', 'Gerechtsdeurwaarders', 'Gerechtsdeurwaarders', 'Beheer_SNG', 'UWV', 'Beheer_UWV', 'vervallen autorisatie', '020.080.01', 'N10');
INSERT INTO "public"."uitwisselingen" VALUES ('301', '001', '0020', '0080', 'Inkomstenverhoudingen', 'UWV', 'Gerechtsdeurwaarders', 'UWV', 'Beheer_UWV', 'Gerechtsdeurwaarders', 'Beheer_SNG', 'vervallen autorisatie', '020.080.01', 'N10');
INSERT INTO "public"."uitwisselingen" VALUES ('420', '331', '0020', '0080', 'Inkomstenverhoudingen', 'UWV', 'Gerechtsdeurwaarders', 'UWV', 'Beheer_UWV', 'Gerechtsdeurwaarders', 'Beheer_SNG', 'vervallen autorisatie', '020.080.01', 'N10');
INSERT INTO "public"."uitwisselingen" VALUES ('423', '321', '0020', '0060', 'Inkomstenverhoudingen', 'UWV', 'LBIO', 'UWV', 'Beheer_UWV', 'LBIO', 'Beheer_LBIO', 'autorisatie', '020.060.01', 'N10');
INSERT INTO "public"."uitwisselingen" VALUES ('424', '321', '0020', '0060', 'Inkomstenverhoudingen', 'UWV', 'LBIO', 'UWV', 'Beheer_UWV', 'LBIO', 'Beheer_LBIO', 'autorisatie', '020.060.01', 'N10');
INSERT INTO "public"."uitwisselingen" VALUES ('401', '201', '0020', '0150', 'Inkomstenverhoudingen', 'UWV', 'ZINL', 'UWV', 'Beheer_UWV', 'ZINL', 'Beheer_Zorginstituut Nederland', 'vervallen autorisatie', '020.150.02', 'N22, N10');
INSERT INTO "public"."uitwisselingen" VALUES ('601', '104', '0070', '0062', 'Inkomensgegevens', 'Belastingdienst', 'Raad voor Rechtsbijstand', 'Raad voor Rechtsbijstand', 'Beheer_RVR', 'Belastingdienst', 'Beheer_BD_Incidenten', 'autorisatie', '070.062.02', null);
INSERT INTO "public"."uitwisselingen" VALUES ('602', '105', '0070', '0062', 'Inkomensgegevens', 'Belastingdienst', 'Raad voor Rechtsbijstand', 'Belastingdienst', 'Beheer_BD_Incidenten', 'Raad voor Rechtsbijstand', 'Beheer_RVR', 'autorisatie', '070.062.02', null);
INSERT INTO "public"."uitwisselingen" VALUES ('368', '002', '0070', '0062', 'Inkomensantwoord (BRI)', 'Belastingdienst', 'Raad voor Rechtsbijstand', 'Raad voor Rechtsbijstand', 'Beheer_RVR', 'Belastingdienst', 'Beheer_BD_Incidenten', 'autorisatie', '070.062.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('369', '002', '0070', '0062', 'Inkomensantwoord (BRI)', 'Belastingdienst', 'Raad voor Rechtsbijstand', 'Belastingdienst', 'Beheer_BD_Incidenten', 'Raad voor Rechtsbijstand', 'Beheer_RVR', 'autorisatie', '070.062.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('370', '002', '0070', '0062', 'Inkomensantwoord (BRI)', 'Belastingdienst', 'Raad voor Rechtsbijstand', 'Belastingdienst', 'Beheer_BD_Incidenten', 'Raad voor Rechtsbijstand', 'Beheer_RVR', 'autorisatie', '070.062.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('371', '002', '0070', '0062', 'Inkomensantwoord (BRI)', 'Belastingdienst', 'Raad voor Rechtsbijstand', 'Belastingdienst', 'Beheer_BD_Incidenten', 'Raad voor Rechtsbijstand', 'Beheer_RVR', 'autorisatie', '070.062.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('010', '001', '0110', '0030', 'Onderwijs', 'DUO', 'SVB', 'SVB', 'Beheer_SVB', 'DUO', 'Beheer_DUO', 'vervallen autorisatie', '110.030.02', null);
INSERT INTO "public"."uitwisselingen" VALUES ('331', '001', '0110', '0030', 'Onderwijs', 'DUO', 'SVB', 'DUO', 'Beheer_DUO', 'SVB', 'Beheer_SVB', 'vervallen autorisatie', '110.030.02', null);
INSERT INTO "public"."uitwisselingen" VALUES ('332', '001', '0110', '0030', 'Onderwijs', 'DUO', 'SVB', 'DUO', 'Beheer_DUO', 'SVB', 'Beheer_SVB', 'vervallen autorisatie', '110.030.02', null);
INSERT INTO "public"."uitwisselingen" VALUES ('406', '100', '0150', '0020', 'Loonbeslag wanbetalers', 'ZINL', 'UWV', 'ZINL', 'Beheer_Zorginstituut Nederland', 'UWV', 'Beheer_UWV', 'vervallen autorisatie', '150.020.01', 'N22');
INSERT INTO "public"."uitwisselingen" VALUES ('334', '001', '0110', '0030', 'Onderwijs', 'DUO', 'SVB', 'DUO', 'Beheer_DUO', 'SVB', 'Beheer_SVB', 'vervallen autorisatie', '110.030.02', null);
INSERT INTO "public"."uitwisselingen" VALUES ('407', '100', '0150', '0020', 'Loonbeslag wanbetalers', 'ZINL', 'UWV', 'ZINL', 'Beheer_Zorginstituut Nederland', 'UWV', 'Beheer_UWV', 'vervallen autorisatie', '150.020.01', 'N22');
INSERT INTO "public"."uitwisselingen" VALUES ('341', '002', '0110', '0030', 'Onderwijs', 'DUO', 'SVB', 'DUO', 'Beheer_DUO', 'SVB', 'Beheer_SVB', 'vervallen autorisatie', '110.030.02', null);
INSERT INTO "public"."uitwisselingen" VALUES ('408', '060', '0150', '0020', 'Loonbeslag wanbetalers', 'ZINL', 'UWV', 'UWV', 'Beheer_UWV', 'ZINL', 'Beheer_Zorginstituut Nederland', 'vervallen autorisatie', '150.020.01', 'N22');
INSERT INTO "public"."uitwisselingen" VALUES ('367', '001', '0030', '0050', 'Onverzekerden', 'SVB', 'CVZ', 'SVB', 'Beheer_SVB', 'CVZ', 'Beheer_CVZ', 'vervallen autorisatie', '030.050.02', null);
INSERT INTO "public"."uitwisselingen" VALUES ('366', '001', '0030', '0050', 'Onverzekerden', 'SVB', 'CVZ', 'SVB', 'Beheer_SVB', 'CVZ', 'Beheer_CVZ', 'vervallen autorisatie', '030.050.02', null);
INSERT INTO "public"."uitwisselingen" VALUES ('341', '001', '0110', '0030', 'Onderwijs', 'DUO', 'SVB', 'DUO', 'Beheer_DUO', 'SVB', 'Beheer_SVB', 'vervallen autorisatie', '110.030.02', null);
INSERT INTO "public"."uitwisselingen" VALUES ('002', '002', '0110', '0041', 'Onderwijs', 'DUO', 'Inlichtingenbureau', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'DUO', 'Beheer_DUO', 'autorisatie', '110.041.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('307', '002', '0110', '0041', 'Onderwijs', 'DUO', 'Inlichtingenbureau', 'DUO', 'Beheer_DUO', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'autorisatie', '110.041.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('333', '001', '0110', '0030', 'Onderwijs', 'DUO', 'SVB', 'DUO', 'Beheer_DUO', 'SVB', 'Beheer_SVB', 'autorisatie', '110.030.02', null);
INSERT INTO "public"."uitwisselingen" VALUES ('372', '003', '0510', '0070', 'Landelijke Registratie Kinderopvang', 'Digikoppeling / DUO', 'Belastingdienst', 'Digikoppeling / DUO', 'Beheer_DUO_LRK', 'Belastingdienst', 'Beheer_BD_Incidenten', 'autorisatie', '510.070.02', 'N39');
INSERT INTO "public"."uitwisselingen" VALUES ('704', '001', '0130', '0120', 'Melding visserij', 'Digipoort', 'CBS', 'Digipoort', 'Beheer_OTP', 'CBS', 'Beheer_CBS', 'vervallen autorisatie', '130.120.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('336', '002', '0030', '0070', 'Kindgebonden Budget', 'SVB', 'Belastingdienst', 'SVB', 'Beheer_SVB', 'Belastingdienst', 'Beheer_BD_Incidenten', 'autorisatie', '030.070.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('337', '002', '0030', '0070', 'Kindgebonden Budget', 'SVB', 'Belastingdienst', 'SVB', 'Beheer_SVB', 'Belastingdienst', 'Beheer_BD_Incidenten', 'autorisatie', '030.070.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('718', '001', '0070', '0120', 'KIS EORI levering Douane aan CBS', 'Belastingdienst (Douane)', 'CBS', 'Belastingdienst (Douane)', 'Beheer_BD_Incidenten', 'CBS', 'Beheer_CBS', 'autorisatie', '070.120.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('501', '94B', '0500', '0030', 'Pensioenen', 'sTESTA', 'SVB', 'sTESTA', 'Beheer_???', 'SVB', 'Beheer_SVB', 'autorisatie', '500.030.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('502', '94B', '0500', '0030', 'Pensioenen', 'sTESTA', 'SVB', 'sTESTA', 'Beheer_???', 'SVB', 'Beheer_SVB', 'autorisatie', '500.030.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('551', '94B', '0500', '0030', 'Pensioenen', 'sTESTA', 'SVB', 'sTESTA', 'Beheer_???', 'SVB', 'Beheer_SVB', 'autorisatie', '500.030.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('ctr', '94B', '0500', '0030', 'Pensioenen', 'sTESTA', 'SVB', 'SVB', 'Beheer_SVB', 'sTESTA', 'Beheer_???', 'autorisatie', '500.030.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('int', '94B', '0500', '0030', 'Pensioenen', 'sTESTA', 'SVB', 'SVB', 'Beheer_SVB', 'sTESTA', 'Beheer_???', 'autorisatie', '500.030.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('339', '002', '0030', '0070', 'Kindgebonden Budget', 'SVB', 'Belastingdienst', 'SVB', 'Beheer_SVB', 'Belastingdienst', 'Beheer_BD_Incidenten', 'autorisatie', '030.070.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('719', '001', '0060', '0070', 'Strafafdoening', 'Openbaar Ministerie', 'Belastingdienst (Douane)', 'Openbaar Ministerie', 'Beheer_OM_strafbeschikking', 'Belastingdienst (Douane)', 'Beheer_BD_Incidenten', 'autorisatie', '060.070.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('362', '002', '0050', '0080', 'Wanbetalers', 'CVZ', 'PRC Gerechtsdeurwaarders', 'CVZ', 'Beheer_CVZ', 'PRC Gerechtsdeurwaarders', 'Beheer_PRCdeurwaarders', 'vervallen autorisatie', '050.080.01', 'N105');
INSERT INTO "public"."uitwisselingen" VALUES ('777', '001', '0070', '0510', 'Service Bericht Aanslag (SBA)', 'Belastingdienst', 'Digikoppeling / Digipoort', 'Digikoppeling / KvK', 'Beheer_KvK', 'Belastingdienst', 'Beheer_BD_Incidenten', 'autorisatie', '070.510.01', 'N19');
INSERT INTO "public"."uitwisselingen" VALUES ('707', '001', '0500', '0050', 'Verrekening zorgkosten', 'sTESTA', 'Zorgverzekeraars', 'sTESTA', 'Beheer_???', 'Zorgverzekeraars', 'Beheer_Zorginstituut Nederland', 'vervallen autorisatie', '500.050.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('658', '103', '0020', '0041', 'SUWI 2', 'UWV', 'Inlichtingenbureau', 'UWV', 'Beheer_CWI', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'vervallen autorisatie', '020.041.03', null);
INSERT INTO "public"."uitwisselingen" VALUES ('652', '101', '0041', '0020', 'SUWI 2', 'Inlichtingenbureau', 'UWV', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'UWV', 'Beheer_CWI', 'vervallen autorisatie', '041.020.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('651', '116', '0020', '0041', 'SUWI 2', 'UWV', 'Inlichtingenbureau', 'UWV', 'Beheer_CWI', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'vervallen autorisatie', '020.041.03', null);
INSERT INTO "public"."uitwisselingen" VALUES ('702', '001', '0130', '0070', 'Renseigneringen van banken en verzekeringen', 'Digipoort', 'Belastingdienst', 'Digipoort', 'Beheer_OTP', 'Belastingdienst', 'Beheer_BD_Incidenten', 'autorisatie', '130.070.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('400', '310', '0020', '0150', 'Inkomstenverhoudingen', 'UWV', 'ZINL', 'ZINL', 'Beheer_Zorginstituut Nederland', 'UWV', 'Beheer_UWV', 'autorisatie', '020.150.02', 'N22, N10');
INSERT INTO "public"."uitwisselingen" VALUES ('703', '001', '0130', '0070', 'Renseigneringen van banken en verzekeringen', 'Digipoort', 'Belastingdienst', 'Digipoort', 'Beheer_OTP', 'Belastingdienst', 'Beheer_BD_Incidenten', 'autorisatie', '130.070.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('653', '101', '0020', '0041', 'SUWI 2', 'UWV', 'Inlichtingenbureau', 'UWV', 'Beheer_CWI', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'vervallen autorisatie', '020.041.03', null);
INSERT INTO "public"."uitwisselingen" VALUES ('657', '133', '0020', '0041', 'SUWI 2', 'UWV', 'Inlichtingenbureau', 'UWV', 'Beheer_CWI', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'vervallen autorisatie', '020.041.03', null);
INSERT INTO "public"."uitwisselingen" VALUES ('659', '101', '0041', '0020', 'SUWI 2', 'Inlichtingenbureau', 'UWV', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'UWV', 'Beheer_CWI', 'vervallen autorisatie', '041.020.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('660', '101', '0041', '0020', 'SUWI 2', 'Inlichtingenbureau', 'UWV', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'UWV', 'Beheer_CWI', 'vervallen autorisatie', '041.020.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('661', '102', '0041', '0020', 'SUWI 2', 'Inlichtingenbureau', 'UWV', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'UWV', 'Beheer_CWI', 'vervallen autorisatie', '041.020.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('662', '102', '0041', '0020', 'SUWI 2', 'Inlichtingenbureau', 'UWV', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'UWV', 'Beheer_CWI', 'vervallen autorisatie', '041.020.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('669', '205', '0020', '0041', 'SUWI 3', 'UWV', 'Inlichtingenbureau', 'UWV', 'Beheer_CWI', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'vervallen autorisatie', '020.041.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('669', '212', '0020', '0041', 'SUWI 3', 'UWV', 'Inlichtingenbureau', 'UWV', 'Beheer_CWI', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'vervallen autorisatie', '020.041.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('012', '001', '0041', '0030', 'Samenlooprapportages', 'Inlichtingenbureau', 'SVB', 'SVB', 'Beheer_SVB', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'autorisatie', '041.030.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('355', '001', '0041', '0030', 'Samenlooprapportages', 'Inlichtingenbureau', 'SVB', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'SVB', 'Beheer_SVB', 'autorisatie', '041.030.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('655', '100', '0041', '0020', 'SUWI 2', 'Inlichtingenbureau', 'UWV', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'UWV', 'Beheer_CWI', 'autorisatie', '041.020.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('654', '101', '0020', '0041', 'SUWI 2', 'UWV', 'Inlichtingenbureau', 'UWV', 'Beheer_CWI', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'autorisatie', '020.041.03', null);
INSERT INTO "public"."uitwisselingen" VALUES ('656', '102', '0020', '0041', 'SUWI 2', 'UWV', 'Inlichtingenbureau', 'UWV', 'Beheer_CWI', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'autorisatie', '020.041.03', null);
INSERT INTO "public"."uitwisselingen" VALUES ('663', '103', '0020', '0041', 'SUWI 3', 'UWV', 'Inlichtingenbureau', 'UWV', 'Beheer_CWI', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'autorisatie', '020.041.02', null);
INSERT INTO "public"."uitwisselingen" VALUES ('664', '102', '0020', '0041', 'SUWI 3', 'UWV', 'Inlichtingenbureau', 'UWV', 'Beheer_CWI', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'autorisatie', '020.041.02', null);
INSERT INTO "public"."uitwisselingen" VALUES ('471', '201', '0020', '0050', 'Inkomstenverhoudingen', 'UWV', 'CVZ', 'UWV', 'Beheer_UWV', 'CVZ', 'Beheer_CVZ', 'vervallen autorisatie', null, null);
INSERT INTO "public"."uitwisselingen" VALUES ('385', '001', '0510', '0070', 'Registratie Niet-Ingezetenen (RNI)', 'Digikoppeling / RvIG', 'Belastingdienst', 'Belastingdienst', 'Beheer_BD_Incidenten', 'Digikoppeling / RvIG', 'Beheer_RNI', 'autorisatie', '510.070.05', null);
INSERT INTO "public"."uitwisselingen" VALUES ('387', '001', '0510', '0070', 'Registratie Niet-Ingezetenen (RNI)', 'Digikoppeling / RvIG', 'Belastingdienst', 'Digikoppeling / RvIG', 'Beheer_RNI', 'Belastingdienst', 'Beheer_BD_Incidenten', 'autorisatie', '510.070.05', null);
INSERT INTO "public"."uitwisselingen" VALUES ('386', '001', '0510', '0070', 'Registratie Niet-Ingezetenen (RNI)', 'Digikoppeling / RvIG', 'Belastingdienst', 'Digikoppeling / RvIG', 'Beheer_RNI', 'Belastingdienst', 'Beheer_BD_Incidenten', 'autorisatie', '510.070.05', null);
INSERT INTO "public"."uitwisselingen" VALUES ('327', '002', '0030', '0120', 'AOW- en Anw-gerechtigden', 'SVB', 'CBS', 'SVB', 'Beheer_SVB', 'CBS', 'Beheer_CBS', 'autorisatie', '030.120.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('738', '001', '0041', '0060', 'Voortvluchtige Veroordeelden', 'Inlichtingenbureau', 'LBIO', 'LBIO', 'Beheer_CJIB', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'autorisatie', '041.060.02', null);
INSERT INTO "public"."uitwisselingen" VALUES ('739', '001', '0041', '0060', 'Voortvluchtige Veroordeelden', 'Inlichtingenbureau', 'LBIO', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'LBIO', 'Beheer_CJIB', 'autorisatie', '041.060.02', null);
INSERT INTO "public"."uitwisselingen" VALUES ('775', '001', '0070', '0060', 'Zorgtoeslag wanbetalers', 'Belastingdienst', 'CJIB', 'CJIB', 'Beheer_CJIB', 'Belastingdienst', 'Beheer_BD_Incidenten', 'autorisatie', '070.060.02', 'N5');
INSERT INTO "public"."uitwisselingen" VALUES ('490', '081', '0020', '0050', 'Inkomstenverhoudingen', 'UWV', 'CVZ', 'UWV', 'Beheer_UWV', 'CVZ', 'Beheer_CVZ', 'vervallen autorisatie', null, null);
INSERT INTO "public"."uitwisselingen" VALUES ('724', '001', '0050', '0070', 'Zorgtoeslagregeling', 'Zorgverzekeraars', 'Belastingdienst', 'Belastingdienst', 'Beheer_BD_Incidenten', 'Zorgverzekeraars', 'Beheer_VECOZO', 'autorisatie', '050.070.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('363', '002', '0050', '0080', 'Wanbetalers', 'CVZ', 'PRC Gerechtsdeurwaarders', 'CVZ', 'Beheer_CVZ', 'PRC Gerechtsdeurwaarders', 'Beheer_PRCdeurwaarders', 'vervallen autorisatie', '050.080.01', 'N105');
INSERT INTO "public"."uitwisselingen" VALUES ('611', '002', '0030', '0510', 'Berichtenbox RDW', 'SVB', 'Digikoppeling / RDW', 'Digikoppeling / RDW', 'Beheer_MijnOverheid_Berichtenbox', 'SVB', 'Beheer_SVB_MijnOverheid', 'autorisatie', '030.510.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('610', '002', '0030', '0510', 'Berichtenbox RDW', 'SVB', 'Digikoppeling / RDW', 'SVB', 'Beheer_SVB_MijnOverheid', 'Digikoppeling / RDW', 'Beheer_MijnOverheid_Berichtenbox', 'autorisatie', '030.510.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('218', '001', '0030', '0140', 'Borderel', 'SVB', 'CAK', 'SVB', 'Beheer_SVB', 'CAK', 'Beheer_CAK', 'autorisatie', '030.140.01', 'N2013-102');
INSERT INTO "public"."uitwisselingen" VALUES ('360', '002', '0050', '0030', 'Wanbetalers', 'Zorgverzekeraars', 'SVB', 'Zorgverzekeraars', 'Beheer_VECOZO', 'SVB', 'Beheer_SVB', 'autorisatie', '050.030.03', 'N27');
INSERT INTO "public"."uitwisselingen" VALUES ('771', '001', '0070', '0060', 'Zorgtoeslag wanbetalers', 'Belastingdienst', 'CJIB', 'Belastingdienst', 'Beheer_BD_Incidenten', 'CJIB', 'Beheer_CJIB', 'autorisatie', '070.060.02', 'N5');
INSERT INTO "public"."uitwisselingen" VALUES ('725', '001', '0050', '0070', 'Zorgtoeslagregeling', 'Zorgverzekeraars', 'Belastingdienst', 'Zorgverzekeraars', 'Beheer_VECOZO', 'Belastingdienst', 'Beheer_BD_Incidenten', 'autorisatie', '050.070.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('015', '001', '0050', '0030', 'Wanbetalers', 'Zorgverzekeraars', 'SVB', 'SVB', 'Beheer_SVB', 'Zorgverzekeraars', 'Beheer_VECOZO', 'autorisatie', '050.030.02', null);
INSERT INTO "public"."uitwisselingen" VALUES ('772', '001', '0070', '0060', 'Zorgtoeslag wanbetalers', 'Belastingdienst', 'CJIB', 'Belastingdienst', 'Beheer_BD_Incidenten', 'CJIB', 'Beheer_CJIB', 'autorisatie', '070.060.02', 'N5');
INSERT INTO "public"."uitwisselingen" VALUES ('013', '001', '0050', '0140', 'WTCG (Wet tegemoetkoming chronisch zieken en gehandicapten)', 'Zorgverzekeraars', 'CAK', 'CAK', 'Beheer_CAK_WTCG', 'Zorgverzekeraars', 'Beheer_VECOZO', 'autorisatie', '050.140.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('323', '001', '0020', '0120', 'Werkzoekenden', 'UWV', 'CBS', 'UWV', 'Beheer_UWV', 'CBS', 'Beheer_CBS', 'autorisatie', '020.120.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('361', '001', '0050', '0030', 'Wanbetalers', 'Zorgverzekeraars', 'SVB', 'Zorgverzekeraars', 'Beheer_VECOZO', 'SVB', 'Beheer_SVB', 'autorisatie', '050.030.02', null);
INSERT INTO "public"."uitwisselingen" VALUES ('359', '001', '0050', '0140', 'WTCG (Wet tegemoetkoming chronisch zieken en gehandicapten)', 'Zorgverzekeraars', 'CAK', 'Zorgverzekeraars', 'Beheer_VECOZO', 'CAK', 'Beheer_CAK_WTCG', 'autorisatie', '050.140.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('373', '002', '0150', '0060', 'Wanbetalers', 'ZINL', 'CJIB', 'ZINL', 'Beheer_Zorginstituut Nederland', 'CJIB', 'Beheer_CJIB', 'autorisatie', '150.060.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('401', '151', '0020', '0050', 'Inkomstenverhoudingen', 'UWV', 'CVZ', 'UWV', 'Beheer_UWV', 'CVZ', 'Beheer_CVZ', 'vervallen autorisatie', null, null);
INSERT INTO "public"."uitwisselingen" VALUES ('406', '120', '0150', '0020', 'Loonbeslag wanbetalers', 'ZINL', 'UWV', 'ZINL', 'Beheer_Zorginstituut Nederland', 'UWV', 'Beheer_UWV', 'autorisatie', '150.020.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('362', '002', '0150', '0080', 'Wanbetalers', 'ZINL', 'PRC Gerechtsdeurwaarders', 'ZINL', 'Beheer_Zorginstituut Nederland', 'PRC Gerechtsdeurwaarders', 'Beheer_PRCdeurwaarders', 'autorisatie', '150.080.01', 'N105');
INSERT INTO "public"."uitwisselingen" VALUES ('363', '002', '0150', '0080', 'Wanbetalers', 'ZINL', 'PRC Gerechtsdeurwaarders', 'ZINL', 'Beheer_Zorginstituut Nederland', 'PRC Gerechtsdeurwaarders', 'Beheer_PRCdeurwaarders', 'autorisatie', '150.080.01', 'N105');
INSERT INTO "public"."uitwisselingen" VALUES ('407', '120', '0150', '0020', 'Loonbeslag wanbetalers', 'ZINL', 'UWV', 'ZINL', 'Beheer_Zorginstituut Nederland', 'UWV', 'Beheer_UWV', 'autorisatie', '150.020.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('386', '001', '0512', '0070', 'Registratie Niet-Ingezetenen (RNI)', 'Digikoppeling / BPR', 'Belastingdienst', 'Digikoppeling / BPR', 'Beheer_RNI', 'Belastingdienst', 'Beheer_BD_Incidenten', 'vervallen autorisatie', '510.070.05', null);
INSERT INTO "public"."uitwisselingen" VALUES ('408', '080', '0150', '0020', 'Loonbeslag wanbetalers', 'ZINL', 'UWV', 'UWV', 'Beheer_UWV', 'ZINL', 'Beheer_Zorginstituut Nederland', 'autorisatie', '150.020.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('364', '002', '0050', '0080', 'Wanbetalers', 'CVZ', 'PRC Gerechtsdeurwaarders', 'PRC Gerechtsdeurwaarders', 'Beheer_PRCdeurwaarders', 'CVZ', 'Beheer_CVZ', 'vervallen autorisatie', '050.080.01', 'N105');
INSERT INTO "public"."uitwisselingen" VALUES ('715', '001', '0070', '0510', 'Presentiebestand (NHR)', 'Belastingdienst', 'Digikoppeling / KvK', 'Belastingdienst', 'Beheer_BD_Incidenten', 'Digikoppeling / KvK', 'Beheer_KvK', 'autorisatie', '070.510.03', null);
INSERT INTO "public"."uitwisselingen" VALUES ('709', '001', '0512', '0120', 'Digilevering (NHR)', 'Digikoppeling / KvK', 'CBS', 'Digikoppeling / KvK', 'Beheer_???', 'CBS', 'Beheer_CBS', 'vervallen autorisatie', '510.120.02', 'N37');
INSERT INTO "public"."uitwisselingen" VALUES ('389', '001', '0512', '0070', 'Wijziging Uitvoering Registratiewet 1970 (WUR)', 'Digikoppeling / KNB', 'Belastingdienst', 'Digikoppeling / KNB', 'Beheer_KNB', 'Belastingdienst', 'Beheer_BD_Incidenten', 'vervallen autorisatie', '510.070.04', 'N15');
INSERT INTO "public"."uitwisselingen" VALUES ('736', '001', '0512', '0070', 'Wijziging Uitvoering Registratiewet 1970 (WUR)', 'Digikoppeling / KNB', 'Belastingdienst', 'Digikoppeling / KNB', 'Beheer_KNB', 'Belastingdienst', 'Beheer_BD_Incidenten', 'vervallen autorisatie', '510.070.04', 'N15');
INSERT INTO "public"."uitwisselingen" VALUES ('720', '001', '0512', '0070', 'eFactureren', 'Digikoppeling / Digipoort', 'Belastingdienst', 'Belastingdienst', 'Beheer_BD_Incidenten', 'Digikoppeling / Digipoort', 'Beheer_???', 'vervallen autorisatie', '510.070.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('721', '001', '0512', '0070', 'eFactureren', 'Digikoppeling / Digipoort', 'Belastingdienst', 'Digikoppeling / Digipoort', 'Beheer_???', 'Belastingdienst', 'Beheer_BD_Incidenten', 'vervallen autorisatie', '510.070.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('387', '001', '0512', '0070', 'Registratie Niet-Ingezetenen (RNI)', 'Digikoppeling / BPR', 'Belastingdienst', 'Digikoppeling / BPR', 'Beheer_RNI', 'Belastingdienst', 'Beheer_BD_Incidenten', 'vervallen autorisatie', '510.070.05', null);
INSERT INTO "public"."uitwisselingen" VALUES ('776', '001', '0070', '0512', 'Service Bericht Aanslag (SBA)', 'Belastingdienst', 'Digikoppeling / Digipoort', 'Belastingdienst', 'Beheer_BD_Incidenten', 'Digikoppeling / KvK', 'Beheer_KvK', 'vervallen autorisatie', '070.510.01', 'N19');
INSERT INTO "public"."uitwisselingen" VALUES ('777', '001', '0070', '0512', 'Service Bericht Aanslag (SBA)', 'Belastingdienst', 'Digikoppeling / Digipoort', 'Digikoppeling / KvK', 'Beheer_KvK', 'Belastingdienst', 'Beheer_BD_Incidenten', 'vervallen autorisatie', '070.510.01', 'N19');
INSERT INTO "public"."uitwisselingen" VALUES ('374', '002', '0150', '0060', 'Wanbetalers', 'ZINL', 'CJIB', 'CJIB', 'Beheer_CJIB', 'ZINL', 'Beheer_Zorginstituut Nederland', 'autorisatie', '150.060.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('347', '001', '0070', '0030', 'PH 32', 'Belastingdienst', 'SVB', 'Belastingdienst', 'Beheer_BD_Incidenten', 'SVB', 'Beheer_SVB', 'autorisatie', '070.030.04', null);
INSERT INTO "public"."uitwisselingen" VALUES ('375', '001', '0150', '0060', 'Wanbetalers', 'ZINL', 'CJIB', 'CJIB', 'Beheer_CJIB', 'ZINL', 'Beheer_Zorginstituut Nederland', 'autorisatie', '150.060.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('338', '001', '0070', '0030', 'Kindertoeslag', 'Belastingdienst', 'SVB', 'Belastingdienst', 'Beheer_BD_Incidenten', 'SVB', 'Beheer_SVB', 'vervallen autorisatie', null, null);
INSERT INTO "public"."uitwisselingen" VALUES ('364', '002', '0150', '0080', 'Wanbetalers', 'ZINL', 'PRC Gerechtsdeurwaarders', 'PRC Gerechtsdeurwaarders', 'Beheer_PRCdeurwaarders', 'ZINL', 'Beheer_Zorginstituut Nederland', 'autorisatie', '150.080.01', 'N105');
INSERT INTO "public"."uitwisselingen" VALUES ('409', '061', '0020', '0150', 'Digitale Betaalspecificatie', 'UWV', 'ZINL', 'UWV', 'Beheer_UWV', 'ZINL', 'Beheer_Zorginstituut Nederland', 'autorisatie', '020.150.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('401', '310', '0020', '0150', 'Inkomstenverhoudingen', 'UWV', 'ZINL', 'UWV', 'Beheer_UWV', 'ZINL', 'Beheer_Zorginstituut Nederland', 'autorisatie', '020.150.02', 'N22, N10');
INSERT INTO "public"."uitwisselingen" VALUES ('490', '241', '0020', '0150', 'Inkomstenverhoudingen', 'UWV', 'ZINL', 'UWV', 'Beheer_UWV', 'ZINL', 'Beheer_Zorginstituut Nederland', 'autorisatie', '020.150.02', 'N22, N10');
INSERT INTO "public"."uitwisselingen" VALUES ('801', '001', '0070', '0060', 'Strafafdoening', 'Belastingdienst (Douane)', 'Openbaar Ministerie', 'Belastingdienst (Douane)', 'Beheer_BD_Incidenten', 'Openbaar Ministerie', 'Beheer_OM_strafbeschikking', 'autorisatie', '070.060.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('802', '001', '0070', '0060', 'Strafafdoening', 'Belastingdienst (Douane)', 'Openbaar Ministerie', 'Belastingdienst (Douane)', 'Beheer_BD_Incidenten', 'Openbaar Ministerie', 'Beheer_OM_strafbeschikking', 'autorisatie', '070.060.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('804', '001', '0070', '0060', 'Strafafdoening', 'Belastingdienst (Douane)', 'Openbaar Ministerie', 'Belastingdienst (Douane)', 'Beheer_BD_Incidenten', 'Openbaar Ministerie', 'Beheer_OM_strafbeschikking', 'autorisatie', '070.060.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('383', '001', '0150', '0050', 'Ambtshalve verzekerden', 'ZINL', 'Zorgverzekeraars', 'Zorgverzekeraars', 'Beheer_VECOZO', 'ZINL', 'Beheer_Zorginstituut Nederland', 'autorisatie', '150.050.02', null);
INSERT INTO "public"."uitwisselingen" VALUES ('773', '001', '0070', '0060', 'Zorgtoeslag wanbetalers', 'Belastingdienst', 'CJIB', 'Belastingdienst', 'Beheer_BD_Incidenten', 'CJIB', 'Beheer_CJIB', 'autorisatie', '070.060.02', 'N5');
INSERT INTO "public"."uitwisselingen" VALUES ('774', '001', '0070', '0060', 'Zorgtoeslag wanbetalers', 'Belastingdienst', 'CJIB', 'Belastingdienst', 'Beheer_BD_Incidenten', 'CJIB', 'Beheer_CJIB', 'autorisatie', '070.060.02', 'N5');
INSERT INTO "public"."uitwisselingen" VALUES ('770', '001', '0070', '0060', 'Zorgtoeslag wanbetalers', 'Belastingdienst', 'CJIB', 'Belastingdienst', 'Beheer_BD_Incidenten', 'CJIB', 'Beheer_CJIB', 'autorisatie', '070.060.02', 'N5');
INSERT INTO "public"."uitwisselingen" VALUES ('338', '002', '0070', '0030', 'Kindgebonden Budget', 'Belastingdienst', 'SVB', 'Belastingdienst', 'Beheer_BD_Incidenten', 'SVB', 'Beheer_SVB', 'autorisatie', '070.030.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('776', '001', '0070', '0510', 'Service Bericht Aanslag (SBA)', 'Belastingdienst', 'Digikoppeling / Digipoort', 'Belastingdienst', 'Beheer_BD_Incidenten', 'Digikoppeling / KvK', 'Beheer_KvK', 'autorisatie', '070.510.01', 'N19');
INSERT INTO "public"."uitwisselingen" VALUES ('372', '004', '0510', '0070', 'Landelijke Registratie Kinderopvang', 'Digikoppeling / DUO', 'Belastingdienst', 'Digikoppeling / DUO', 'Beheer_DUO_LRK', 'Belastingdienst', 'Beheer_BD_Incidenten', 'autorisatie', '510.070.02', 'N225');
INSERT INTO "public"."uitwisselingen" VALUES ('378', '001', '0050', '0150', 'Wanbetalers', 'Zorgverzekeraars', 'ZINL', 'Zorgverzekeraars', 'Beheer_ZORG', 'ZINL', 'Beheer_Zorginstituut Nederland', 'vervallen autorisatie', '050.150.01', 'N113, N116');
INSERT INTO "public"."uitwisselingen" VALUES ('377', '001', '0050', '0150', 'Wanbetalers', 'Zorgverzekeraars', 'ZINL', 'Zorgverzekeraars', 'Beheer_ZORG', 'ZINL', 'Beheer_Zorginstituut Nederland', 'vervallen autorisatie', '050.150.01', 'N113, N116');
INSERT INTO "public"."uitwisselingen" VALUES ('377', '002', '0050', '0150', 'Wanbetalers', 'Zorgverzekeraars', 'ZINL', 'Zorgverzekeraars', 'Beheer_VECOZO', 'ZINL', 'Beheer_Zorginstituut Nederland', 'autorisatie', '050.150.01', 'N113, N116');
INSERT INTO "public"."uitwisselingen" VALUES ('781', '001', '0150', '0500', 'Verrekening Zorgkosten', 'ZINL', 'sTESTA', 'ZINL', 'Beheer_Zorginstituut Nederland', 'sTESTA', 'Beheer_???', 'autorisatie', '150.500.01', 'N2013-137');
INSERT INTO "public"."uitwisselingen" VALUES ('707', '001', '0500', '0150', 'Verrekening zorgkosten', 'sTESTA', 'ZINL', 'sTESTA', 'Beheer_???', 'ZINL', 'Beheer_Zorginstituut Nederland', 'autorisatie', '500.150.01', 'N2013-137');
INSERT INTO "public"."uitwisselingen" VALUES ('379', '001', '0050', '0150', 'Wanbetalers', 'Zorgverzekeraars', 'ZINL', 'ZINL', 'Beheer_Zorginstituut Nederland', 'Zorgverzekeraars', 'Beheer_ZORG', 'vervallen autorisatie', '050.150.01', 'N113, N116');
INSERT INTO "public"."uitwisselingen" VALUES ('390', '001', '0110', '0030', 'Kostendelersnorm', 'DUO', 'SVB', 'DUO', 'Beheer_DUO', 'SVB', 'Beheer_SVB', 'autorisatie', '110.030.04', 'N2014-249');
INSERT INTO "public"."uitwisselingen" VALUES ('017', '001', '0110', '0030', 'Kostendelersnorm', 'DUO', 'SVB', 'SVB', 'Beheer_SVB', 'DUO', 'Beheer_DUO', 'autorisatie', '110.030.04', 'N2014-249');
INSERT INTO "public"."uitwisselingen" VALUES ('607', '100', '0041', '0080', 'Uitkeringsgegevens', 'Inlichtingenbureau', 'Gerechtsdeurwaarders', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'Gerechtsdeurwaarders', 'Beheer_SNG', 'autorisatie', '041.080.02', 'N2013-133');
INSERT INTO "public"."uitwisselingen" VALUES ('606', '100', '0041', '0080', 'Uitkeringsgegevens', 'Inlichtingenbureau', 'Gerechtsdeurwaarders', 'Gerechtsdeurwaarders', 'Beheer_SNG', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'autorisatie', '041.080.02', 'N2013-133');
INSERT INTO "public"."uitwisselingen" VALUES ('WLZ002', '0100', '0510', '0041', 'WLZ indicatie', 'Digikoppeling / CIZ', 'Inlichtingenbureau', 'Digikoppeling / CIZ', 'Beheer_CIZ', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'autorisatie', '510.041.01', 'N2013-260');
INSERT INTO "public"."uitwisselingen" VALUES ('326', '002', '0030', '0150', 'Gemoedsbezwaarden', 'SVB', 'ZINL', 'SVB', 'Beheer_SVB', 'ZINL', 'Beheer_Zorginstituut_Nederland', 'autorisatie', '030.150.02', 'N2013-148');
INSERT INTO "public"."uitwisselingen" VALUES ('WMO301', '0100', '0050', '0041', 'Toewijzing WMO', 'Zorgverzekeraars', 'Inlichtingenbureau', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'Zorgverzekeraars', 'Beheer_VECOZO', 'autorisatie', '050.041.02', 'N2013-139');
INSERT INTO "public"."uitwisselingen" VALUES ('737', '001', '0512', '0070', 'Wijziging Uitvoering Registratiewet 1970 (WUR)', 'Digikoppeling / KNB', 'Belastingdienst', 'Belastingdienst', 'Beheer_BD_Incidenten', 'Digikoppeling / KNB', 'Beheer_KNB', 'vervallen autorisatie', '510.070.04', 'N15');
INSERT INTO "public"."uitwisselingen" VALUES ('WLZ001', '0100', '0510', '0041', 'WLZ indicatie', 'Digikoppeling / CIZ', 'Inlichtingenbureau', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'Digikoppeling / CIZ', 'Beheer_CIZ', 'autorisatie', '510.041.01', 'N2013-260');
INSERT INTO "public"."uitwisselingen" VALUES ('349', '001', '0070', '0030', 'SCHUNAL (Schuldig nalatig)', 'Belastingdienst', 'SVB', 'Belastingdienst', 'Beheer_BD_Incidenten', 'SVB', 'Beheer_SVB', 'autorisatie', '070.030.02', null);
INSERT INTO "public"."uitwisselingen" VALUES ('379', '002', '0050', '0150', 'Wanbetalers', 'Zorgverzekeraars', 'ZINL', 'ZINL', 'Beheer_Zorginstituut Nederland', 'Zorgverzekeraars', 'Beheer_VECOZO', 'autorisatie', '050.150.01', 'N113, N116');
INSERT INTO "public"."uitwisselingen" VALUES ('358', '001', '0070', '0030', 'SCHUNAL (Schuldig nalatig)', 'Belastingdienst', 'SVB', 'Belastingdienst', 'Beheer_BD_Incidenten', 'SVB', 'Beheer_SVB', 'autorisatie', '070.030.02', null);
INSERT INTO "public"."uitwisselingen" VALUES ('385', '001', '0512', '0070', 'Registratie Niet-Ingezetenen (RNI)', 'Digikoppeling / BPR', 'Belastingdienst', 'Belastingdienst', 'Beheer_BD_Incidenten', 'Digikoppeling / BPR', 'Beheer_RNI', 'vervallen autorisatie', '510.070.05', null);
INSERT INTO "public"."uitwisselingen" VALUES ('378', '002', '0050', '0150', 'Wanbetalers', 'Zorgverzekeraars', 'ZINL', 'Zorgverzekeraars', 'Beheer_VECOZO', 'ZINL', 'Beheer_Zorginstituut Nederland', 'autorisatie', '050.150.01', 'N113, N116');
INSERT INTO "public"."uitwisselingen" VALUES ('376', '001', '0050', '0150', 'Wanbetalers', 'Zorgverzekeraars', 'ZINL', 'Zorgverzekeraars', 'Beheer_ZORG', 'ZINL', 'Beheer_Zorginstituut Nederland', 'vervallen autorisatie', '050.150.01', 'N113, N116');
INSERT INTO "public"."uitwisselingen" VALUES ('353', '002', '0150', '0030', 'Broninhouding wanbetalers', 'ZINL', 'SVB', 'SVB', 'Beheer_SVB', 'ZINL', 'Beheer_Zorginstituut Nederland', 'autorisatie', '150.030.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('354', '002', '0150', '0030', 'Broninhouding wanbetalers', 'ZINL', 'SVB', 'SVB', 'Beheer_SVB', 'ZINL', 'Beheer_Zorginstituut Nederland', 'autorisatie', '150.030.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('WMO302', '0100', '0050', '0041', 'Toewijzing WMO', 'Zorgverzekeraars', 'Inlichtingenbureau', 'Zorgverzekeraars', 'Beheer_VECOZO', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'autorisatie', '050.041.02', 'N2013-139');
INSERT INTO "public"."uitwisselingen" VALUES ('614', '001', '0050', '0030', 'PGB Trekkingsrecht', 'Zorgverzekeraars', 'SVB', 'Zorgverzekeraars', 'Beheer_VECOZO', 'SVB', 'Beheer_SVB', 'autorisatie', '050.030.04', 'N2014-145');
INSERT INTO "public"."uitwisselingen" VALUES ('WMO303', '0100', '0041', '0050', 'Declaratie WMO', 'Inlichtingenbureau', 'Zorgverzekeraars', 'Zorgverzekeraars', 'Beheer_VECOZO', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'autorisatie', '041.050.01', 'N2013-139');
INSERT INTO "public"."uitwisselingen" VALUES ('JW302', '0100', '0050', '0041', 'Toewijzing Jeugd', 'Zorgverzekeraars', 'Inlichtingenbureau', 'Zorgverzekeraars', 'Beheer_VECOZO', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'autorisatie', '050.041.03', 'N2013-139');
INSERT INTO "public"."uitwisselingen" VALUES ('669', '224', '0020', '0041', 'SUWI 3', 'UWV', 'Inlichtingenbureau', 'UWV', 'Beheer_Inlichtingenbureau', 'Inlichtingenbureau', 'Beheer_CWI', 'autorisatie', '020.041.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('JW304', '0100', '0041', '0050', 'Declaratie Jeugd-AWBZ', 'Inlichtingenbureau', 'Zorgverzekeraars', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'Zorgverzekeraars', 'Beheer_VECOZO', 'autorisatie', '041.050.02', 'N2013-139');
INSERT INTO "public"."uitwisselingen" VALUES ('JW322', '0100', '0041', '0050', 'Declaratie Jeugd-GGZ', 'Inlichtingenbureau', 'Zorgverzekeraars', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'Zorgverzekeraars', 'Beheer_VECOZO', 'autorisatie', '041.050.03', 'N2013-139');
INSERT INTO "public"."uitwisselingen" VALUES ('WMO304', '0100', '0041', '0050', 'Declaratie WMO', 'Inlichtingenbureau', 'Zorgverzekeraars', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'Zorgverzekeraars', 'Beheer_VECOZO', 'autorisatie', '041.050.01', 'N2013-139');
INSERT INTO "public"."uitwisselingen" VALUES ('376', '002', '0050', '0150', 'Wanbetalers', 'Zorgverzekeraars', 'ZINL', 'Zorgverzekeraars', 'Beheer_VECOZO', 'ZINL', 'Beheer_Zorginstituut Nederland', 'autorisatie', '050.150.01', 'N113, N116');
INSERT INTO "public"."uitwisselingen" VALUES ('002', '003', '0110', '0041', 'Onderwijs', 'DUO', 'Inlichtingenbureau', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'DUO', 'Beheer_DUO', 'autorisatie', '110.041.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('307', '003', '0110', '0041', 'Onderwijs', 'DUO', 'Inlichtingenbureau', 'DUO', 'Beheer_DUO', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'autorisatie', '110.041.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('501', '94B', '0030', '0500', 'Pensioenen', 'SVB', 'sTESTA', 'SVB', 'Beheer_SVB', 'sTESTA', 'Beheer_???', 'autorisatie', '030.500.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('502', '94B', '0030', '0500', 'Pensioenen', 'SVB', 'sTESTA', 'SVB', 'Beheer_SVB', 'sTESTA', 'Beheer_???', 'autorisatie', '030.500.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('551', '94B', '0030', '0500', 'Pensioenen', 'SVB', 'sTESTA', 'SVB', 'Beheer_SVB', 'sTESTA', 'Beheer_???', 'autorisatie', '030.500.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('ctr', '94B', '0030', '0500', 'Pensioenen', 'SVB', 'sTESTA', 'sTESTA', 'Beheer_???', 'SVB', 'Beheer_SVB', 'autorisatie', '030.500.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('int', '94B', '0030', '0500', 'Pensioenen', 'SVB', 'sTESTA', 'sTESTA', 'Beheer_???', 'SVB', 'Beheer_SVB', 'autorisatie', '030.500.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('340', '002', '0030', '0070', 'Kindgebonden Budget', 'SVB', 'Belastingdienst', 'SVB', 'Beheer_SVB', 'Belastingdienst', 'Beheer_BD_Incidenten', 'autorisatie', '030.070.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('366', '001', '0030', '0150', 'Onverzekerden', 'SVB', 'ZINL', 'SVB', 'Beheer_SVB', 'ZINL', 'Beheer_Zorginstituut Nederland', 'autorisatie', '030.150.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('367', '001', '0030', '0150', 'Onverzekerden', 'SVB', 'ZINL', 'SVB', 'Beheer_SVB', 'ZINL', 'Beheer_Zorginstituut Nederland', 'autorisatie', '030.150.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('345', '003', '0050', '0041', 'Onverzekerden en wanbetalers', 'Zorgverzekeraars', 'Inlichtingenbureau', 'Zorgverzekeraars', 'Beheer_VECOZO', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'autorisatie', '050.041.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('009', '003', '0050', '0041', 'Onverzekerden en wanbetalers', 'Zorgverzekeraars', 'Inlichtingenbureau', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'Zorgverzekeraars', 'Beheer_VECOZO', 'autorisatie', '050.041.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('665', '102', '0020', '0041', 'SUWI 3', 'UWV', 'Inlichtingenbureau', 'UWV', 'Beheer_CWI', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'autorisatie', '020.041.02', null);
INSERT INTO "public"."uitwisselingen" VALUES ('666', '103', '0020', '0041', 'SUWI 3', 'UWV', 'Inlichtingenbureau', 'UWV', 'Beheer_CWI', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'autorisatie', '020.041.02', null);
INSERT INTO "public"."uitwisselingen" VALUES ('666', '111', '0020', '0041', 'SUWI 3', 'UWV', 'Inlichtingenbureau', 'UWV', 'Beheer_CWI', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'autorisatie', '020.041.02', null);
INSERT INTO "public"."uitwisselingen" VALUES ('667', '102', '0020', '0041', 'SUWI 3', 'UWV', 'Inlichtingenbureau', 'UWV', 'Beheer_CWI', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'autorisatie', '020.041.02', null);
INSERT INTO "public"."uitwisselingen" VALUES ('668', '102', '0020', '0041', 'SUWI 3', 'UWV', 'Inlichtingenbureau', 'UWV', 'Beheer_CWI', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'autorisatie', '020.041.02', null);
INSERT INTO "public"."uitwisselingen" VALUES ('606', '100', '0041', '0060', 'Uitkeringsgegevens', 'Inlichtingenbureau', 'LBIO', 'LBIO', 'Beheer_LBIO', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'autorisatie', '041.060.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('607', '100', '0041', '0060', 'Uitkeringsgegevens', 'Inlichtingenbureau', 'LBIO', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'LBIO', 'Beheer_LBIO', 'autorisatie', '041.060.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('005', '001', '0030', '0080', 'Uitkeringsgegevens', 'SVB', 'Gerechtsdeurwaarders', 'Gerechtsdeurwaarders', 'Beheer_SNG', 'SVB', 'Beheer_SVB', 'autorisatie', '030.080.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('318', '001', '0030', '0080', 'Uitkeringsgegevens', 'SVB', 'Gerechtsdeurwaarders', 'SVB', 'Beheer_SVB', 'Gerechtsdeurwaarders', 'Beheer_SNG', 'autorisatie', '030.080.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('322', '001', '0041', '0080', 'Uitkeringsgegevens', 'Inlichtingenbureau', 'Gerechtsdeurwaarders', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'Gerechtsdeurwaarders', 'Beheer_SNG', 'autorisatie', '041.080.01', null);
INSERT INTO "public"."uitwisselingen" VALUES ('JW321', '0100', '0041', '0050', 'Declaratie Jeugd-GGZ', 'Inlichtingenbureau', 'Zorgverzekeraars', 'Zorgverzekeraars', 'Beheer_Inlichtingenbureau ', 'Inlichtingenbureau', 'Beheer_VECOZO', 'autorisatie', '041.050.03', 'N2013-139');
INSERT INTO "public"."uitwisselingen" VALUES ('007', '001', '0041', '0080', 'Uitkeringsgegevens', 'Inlichtingenbureau', 'Gerechtsdeurwaarders', 'Gerechtsdeurwaarders', 'Beheer_SNG', 'Inlichtingenbureau', 'Beheer_Inlichtingenbureau', 'autorisatie', '041.080.01', null);
COMMIT;

-- ----------------------------
--  Primary key structure for table uitwisselingen
-- ----------------------------
ALTER TABLE "public"."uitwisselingen" ADD PRIMARY KEY ("lev", "aan", "ber", "fun");

